linagora/tmail-backend

openpaas-james/apps/memory/README.md
openpaas-james/apps/memory/pom.xml
openpaas-james/apps/memory/src/main/scripts/james-cli
openpaas-james/pom.xml

- Add the CLI as a runtime dependency
- Run a custom java command within the container
- And wrap it in a script to simplify calls

ISSUE-7 JIB & CLI support

---

openpaas-james/apps/memory/pom.xml
openpaas-james/deployment-tests/common/pom.xml
openpaas-james/deployment-tests/common/src/main/java/com/linagora/openpaas/deployment/CliContract.java
openpaas-james/deployment-tests/common/src/main/java/com/linagora/openpaas/deployment/ImapAndSmtpContract.java
openpaas-james/deployment-tests/memory/pom.xml
openpaas-james/deployment-tests/memory/src/test/java/com/linagora/openpaas/deployment/MemoryCliTest.java
openpaas-james/deployment-tests/memory/src/test/java/com/linagora/openpaas/deployment/MemoryImapAndSmtpTest.java
openpaas-james/deployment-tests/memory/src/test/java/com/linagora/openpaas/deployment/OpenpaasJamesMemoryExtension.java
openpaas-james/deployment-tests/pom.xml
openpaas-james/pom.xml

Result of today's MOB
Depends on https://github.com/linagora/james-project/pull/4222

ISSUE-9 Memory deployment tests

---

openpaas-james/deployment-tests/common/src/main/java/com/linagora/openpaas/deployment/JmapContract.java
openpaas-james/deployment-tests/memory/src/test/java/com/linagora/openpaas/deployment/MemoryJmapTest.java

add JMAP contract deployement test on memory

---

Jenkinsfile
README.md
dockerfiles/jenkins-runner/Jenkinsfile

Don't merge, I test PR builds with the CI here

Adapt Jenkinsfile for PR builds on CI

---

openpaas-james/apps/distributed-ldap/src/main/java/com/linagora/openpaas/james/app/DistributedLdapServer.java
openpaas-james/apps/distributed-ldap/src/test/java/com/linagora/openpaas/james/app/DistributedLdapServerTest.java
openpaas-james/apps/distributed/src/main/java/com/linagora/openpaas/james/app/DistributedServer.java
openpaas-james/integration-tests/jmap/distributed-ldap-jmap-integration-tests/src/test/java/com/linagora/openpaas/james/DistributedLdapLinagoraEchoMethodTest.java
openpaas-james/integration-tests/jmap/distributed-ldap-jmap-integration-tests/src/test/java/com/linagora/openpaas/james/DistributedLdapLinagoraFilterGetMethodTest.java

Let's let the CI check that before we merge now :)

Update james-project SHA-1

---

Jenkinsfile

Gonna break for now likely... I didn't update the CI and this PR is not the master branch. I will add additional commits for testing with time

Docker push master

---

README.md

Because I've been a bad dev and forgot to do it...

Drop mentions of distributed-ldap server in the README

---

openpaas-james/apps/distributed/pom.xml
openpaas-james/apps/distributed/src/main/java/com/linagora/openpaas/james/app/DistributedServer.java
openpaas-james/pom.xml

See https://github.com/apache/james-project/pull/330
This drops ActiveMQ from our dependencies <3

ISSUE-47 Remove unneeded modules from DistributedServer

---

openpaas-james/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/openpaas/james/common/LinagoraFilterGetMethodContract.scala
openpaas-james/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/openpaas/james/common/LinagoraFilterSetMethodContract.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/json/FilterSerializer.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/method/FilterGetMethod.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/model/FilterGet.scala

Solving @https://github.com/linagora/openpaas-james/issues/72
need this to be merged first: @https://github.com/apache/james-project/pull/341

ISSUE-72: Filter versioning

---

openpaas-james/mailbox/encrypted/memory/pom.xml
openpaas-james/mailbox/encrypted/memory/src/main/java/com/linagora/openpaas/encrypted/EncryptedMailboxManager.scala
openpaas-james/mailbox/encrypted/memory/src/main/java/com/linagora/openpaas/encrypted/EncryptedMessageManager.scala
openpaas-james/mailbox/encrypted/memory/src/test/java/com/linagora/openpaas/encrypted/EncryptedMessageManagerTest.java
openpaas-james/mailbox/encrypted/memory/src/test/java/com/linagora/openpaas/encrypted/InMemoryKeystoreManagerTest.java

Since the append functions is inside MessageManager, I'm not sure about why we need an EncryptedMailboxManager also...

ISSUE-95 Write an EncryptedMailboxManager

---

openpaas-james/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/openpaas/james/common/LinagoraFilterGetMethodContract.scala
openpaas-james/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/openpaas/james/common/LinagoraFilterSetMethodContract.scala
openpaas-james/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/openpaas/james/common/probe/JmapGuiceCustomProbe.java
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/json/FilterSerializer.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/method/FilterSetMethod.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/model/FilterGet.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/model/FilterSet.scala

need this to be merged first: https://github.com/apache/james-project/pull/346
Do I need to change "newState" property following versioning change?

ISSUE-73 State implementation for Filter/set method

---

openpaas-james/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/openpaas/james/common/LinagoraKeystoreSetMethodContract.scala
openpaas-james/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/openpaas/james/common/probe/JmapGuiceKeystoreManagerProbe.java
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/json/KeystoreSerializer.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/method/KeystoreSetDestroyPerformer.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/method/KeystoreSetMethod.scala
openpaas-james/jmap/extensions/src/main/scala/com/linagora/openpaas/james/jmap/model/KeystoreSet.scala

a few concerns:
- Since we never check for the key validity, i don't think we will ever run into a "notDestroyed" case.
- Do we allow user to destroy all of their keys? What would be the input parameters in that case? Also if we succeed in deleting all of the keys, how would we be able to return all of the destroyed keys' ID?

ISSUE-94 Keystore/set destroy method

---

tmail-backend/apps/distributed-es6-backport/pom.xml
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/pom.xml
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/pom.xml
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/apps/memory/src/test/java/com/linagora/tmail/james/app/MemoryServerTest.java
tmail-backend/apps/memory/src/test/resources/eml/htmlMail.eml
tmail-backend/mailetcontainer-impl/pom.xml
tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/CompositeProcessorImpl.java
tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/CustomMailetProcessingModule.java
tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/MailetContainerImplModule.java
tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/MailetProcessorImpl.java
tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/MatcherSplitter.java
tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/ProcessorImpl.java
tmail-backend/mailetcontainer-impl/src/test/java/org/apache/james/mailetcontainer/impl/CompositeProcessorImplTest.java
tmail-backend/mailetcontainer-impl/src/test/java/org/apache/james/mailetcontainer/impl/MailetProcessorImplTest.java
tmail-backend/pom.xml

See https://github.com/apache/james-project/pull/448
Requires https://github.com/apache/james-project/pull/451 to be :green_apple:

JAMES-3589 Backport MailetContainerImpl with adequate fix

---

tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/MailetProcessorImpl.java

This makes that ghosted mails are well disposed.

JAMES-3589 Use a builder to reference split mails as encountered

---

tmail-backend/apps/distributed-es6-backport/pom.xml
tmail-backend/apps/distributed/pom.xml
tmail-backend/apps/memory/pom.xml

That way we ease doing profiling :-)

Update glowroot and install async-profiler in TMail docker images

---

tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/MailetContainerImplModule.java

See https://github.com/linagora/james-project/issues/4328

JAMES-3589 Ensure the spooler is started after the mailet container

---

tmail-backend/apps/distributed-es6-backport/pom.xml
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedJamesConfiguration.java
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed-es6-backport/src/test/java/com/linagora/tmail/james/app/CombinedIdentityJamesServerTest.java
tmail-backend/apps/distributed-es6-backport/src/test/java/com/linagora/tmail/james/app/DistributedServerTest.java
tmail-backend/apps/distributed-es6-backport/src/test/java/com/linagora/tmail/james/app/EncryptedDistributedServerTest.java
tmail-backend/apps/distributed/pom.xml
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedJamesConfiguration.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/CombinedIdentityJamesServerTest.java
tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/DistributedServerTest.java
tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/EncryptedDistributedServerTest.java
tmail-backend/combined-identity/pom.xml
tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/CombinedUserDAO.java
tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/CombinedUsersRepository.java
tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/CombinedUsersRepositoryModule.java
tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/UsersRepositoryClassProbe.java
tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/UsersRepositoryModuleChooser.java
tmail-backend/combined-identity/src/test/java/com/linagora/tmail/combined/identity/CombinedUsersRepositoryContract.java
tmail-backend/combined-identity/src/test/java/com/linagora/tmail/combined/identity/CombinedUsersRepositoryTest.java
tmail-backend/combined-identity/src/test/resources/ldif-files/Dockerfile
tmail-backend/combined-identity/src/test/resources/ldif-files/populate.ldif
tmail-backend/pom.xml

https://github.com/linagora/tmail-backend/issues/157

ISSUE-157 Combined Identity use LDAP for authentication only and all other mechanisms use a local database

---

tmail-backend/mailbox/encrypted/api/pom.xml
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedEmailContentStore.scala
tmail-backend/mailbox/encrypted/api/src/test/scala/com/linagora/tmail/encrypted/EncryptedEmailContentStoreContract.scala
tmail-backend/mailbox/encrypted/memory/pom.xml
tmail-backend/mailbox/encrypted/memory/src/main/java/com/linagora/tmail/encrypted/InMemoryEncryptedEmailContentStore.scala
tmail-backend/mailbox/encrypted/memory/src/test/java/com/linagora/tmail/encrypted/InMemoryEncryptedEmailContentStoreTest.java

Ref: https://github.com/linagora/tmail-backend/issues/117

ISSUE-117 PGP: MemoryEncryptedEmailContentStore

---

tmail-backend/apps/distributed/src/main/conf/usersrepository.xml

Ref: https://github.com/linagora/tmail-backend/issues/157

ISSUE-157 Combined Identity - update sample config file

---

tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedEmailContentStore.scala
tmail-backend/mailbox/encrypted/cassandra/pom.xml
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/table/CassandraEncryptedEmailContentStore.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/table/CassandraEncryptedEmailDAO.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/table/CassandraEncryptedEmailStoreModule.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/table/EncryptedEmailTable.scala
tmail-backend/mailbox/encrypted/cassandra/src/test/java/com/linagora/tmail/encrypted/cassandra/CassandraEncryptedEmailContentStoreTest.java

Ref https://github.com/linagora/tmail-backend/issues/118

ISSUE-118 PGP: CassandraEncryptedEmailContentStore

---

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEncryptedEmailFastViewGetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/pom.xml
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EncryptHelper.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEncryptedEmailFastViewGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/probe/JmapGuiceEncryptedEmailContentStoreProbe.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraEncryptedEmailFastViewGetMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/EncryptedEmailSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EncryptedEmailFastViewGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EncryptedEmailGet.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/EncryptedEmailSerializerTest.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/CassandraEncryptedEmailContentStore.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/CassandraEncryptedEmailDAO.scala
tmail-backend/mailbox/encrypted/cassandra/src/test/java/com/linagora/tmail/encrypted/cassandra/CassandraEncryptedEmailContentStoreTest.java
tmail-backend/mailbox/encrypted/memory/src/main/java/com/linagora/tmail/encrypted/InMemoryEncryptedEmailContentStore.scala
tmail-backend/mailbox/encrypted/memory/src/test/java/com/linagora/tmail/encrypted/InMemoryEncryptedEmailContentStoreTest.java

Ref https://github.com/linagora/tmail-backend/issues/122

ISSUE-122 PGP - EncryptedEmailFastView/get Method

---

tmail-backend/mailbox/encrypted/cassandra/pom.xml
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/DeleteEncryptedProjectionHook.java
tmail-backend/mailbox/encrypted/cassandra/src/test/java/com/linagora/tmail/encrypted/cassandra/DeleteEncryptedProjectionHookTest.java

Ref: https://github.com/linagora/tmail-backend/issues/119

ISSUE-119 PGP: EncryptedProjectionCleanupListener

---

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEncryptedEmailDetailedViewGetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EncryptHelper.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEncryptedEmailDetailedViewGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEncryptedEmailFastViewGetMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraEncryptedEmailDetailedViewGetMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/EncryptedEmailSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EncryptedEmailDetailedViewGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EncryptedEmailGet.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/EncryptedEmailSerializerTest.scala

ref https://github.com/linagora/tmail-backend/issues/121

ISSUE-121 PGP - EncryptedEmailDetailedView/get Method

---

tmail-backend/mailbox/elasticsearch-v6/src/main/java/org/apache/james/mailbox/elasticsearch/MailboxMappingFactory.java
tmail-backend/mailbox/elasticsearch-v6/src/main/java/org/apache/james/mailbox/elasticsearch/json/IndexableMessage.java
tmail-backend/mailbox/elasticsearch-v6/src/main/java/org/apache/james/mailbox/elasticsearch/json/JsonMessageConstants.java
tmail-backend/mailbox/elasticsearch-v6/src/main/java/org/apache/james/mailbox/elasticsearch/query/CriterionConverter.java
tmail-backend/mailbox/elasticsearch-v6/src/test/java/org/apache/james/mailbox/elasticsearch/ElasticSearchIntegrationTest.java
tmail-backend/mailbox/encrypted/cassandra/src/test/java/com/linagora/tmail/encrypted/cassandra/DeleteEncryptedProjectionHookTest.java
tmail-backend/mailbox/opendistro-tests/src/test/java/org/apache/james/mailbox/opendistro/OpenDistroIntegrationTest.java

And from there I will be able to tag the release

Update James project SHA1

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEncryptedEmailDetailedViewGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEncryptedEmailFastViewGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraKeystoreGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraKeystoreSetMethodContract.scala
tmail-backend/jmap/extensions/doc/jmapGpgExtension.md
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EncryptedEmailDetailedViewGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EncryptedEmailFastViewGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/KeystoreGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EncryptedEmailGet.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/KeystoreGet.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/EncryptedEmailSerializerTest.scala
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedEmailContentStore.scala
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedMessageManager.scala
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/KeystoreManager.scala
tmail-backend/mailbox/encrypted/api/src/test/scala/com/linagora/tmail/encrypted/EncryptedEmailContentStoreContract.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/CassandraEncryptedEmailContentStore.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/CassandraEncryptedEmailDAO.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/CassandraKeystoreDAO.scala
tmail-backend/mailbox/encrypted/memory/src/main/java/com/linagora/tmail/encrypted/InMemoryEncryptedEmailContentStore.scala

Along the way I do fix some tiny some JMAP spec compliance issues...

ISSUE-192 Specify com:linagora:params:jmap:pgp extension

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEmailSendMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEmailSendMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraEmailSendMethodTest.java
tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/EmailSendSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EmailSendMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EmailSend.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EmailSubmissionHelper.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/EmailSendSerializerTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/Fixture.scala

Ref: https://github.com/linagora/tmail-backend/issues/188

[ISSUE-188] Implement JMAP Email/send

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/longlivedtoken/LongLivedTokenStore.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/longlivedtoken/InMemoryLongLivedTokenStoreTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/longlivedtoken/LongLivedTokenStoreContract.scala

ref https://github.com/linagora/tmail-backend/issues/209

ISSUE-209 LongLivedToken repository (API, memory, contract)

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraLongLivedTokenSetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraLongLivedTokenSetMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraLongLivedTokenSetMethodTest.java
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/longlivedtoken/CassandraLongLivedTokenStore.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/LongLivedTokenSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/longlivedtoken/LongLivedTokenStore.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LongLivedTokenSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/LongLivedTokenSet.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/LongLivedTokenSerializerTest.scala

Ref https://github.com/linagora/tmail-backend/issues/212

ISSUE-212 LongLivedToken/set create

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraLongLivedTokenSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/LongLivedTokenSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/longlivedtoken/LongLivedTokenAuthenticationStrategy.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LongLivedTokenSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/LongLivedTokenSet.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/LongLivedTokenSerializerTest.scala

Ref https://github.com/linagora/tmail-backend/issues/212
https://github.com/linagora/tmail-backend/issues/211
Update token response of  `LongLivedToken/set `

 ISSUE-212 LongLivedToken/set should return token has username and secret

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLongLivedTokenGetTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraLongLivedTokenSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraShortLivedTokenRoutesContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/LongLivedTokenSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/longlivedtoken/LongLivedTokenStore.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LongLivedTokenSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/LongLivedTokenSet.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/LongLivedTokenSerializerTest.scala

ISSUE-216 LongLivedToken/set destroy implementation

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraShortLivedTokenRoutesContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/jwt/ShortLivedTokenRoutes.scala

ref https://github.com/linagora/tmail-backend/issues/214

ISSUE-214 GET /token endpoint should support Basic Auth

---

tmail-backend/guice/protocols/jmap/src/test/java/com/linagora/tmail/module/LinagoraTestJMAPServerModule.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedTicketRoutesTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraShortLivedTokenRoutesContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraTicketAuthenticationContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryTicketAuthenticationTest.java
tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/jwt/ShortLivedTokenRoutes.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FilterGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/KeystoreSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LongLivedTokenSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ticket/TicketAuthenticationStrategy.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ticket/TicketRoutes.scala

Requires https://github.com/apache/james-project/pull/807

JAMES-3680 Ticket capability should use resolved URL

---

tmail-backend/apps/distributed-es6-backport/src/main/conf/jmap.properties
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/conf/jmap.properties
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/conf/jmap.properties
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/guice/protocols/jmap/src/test/java/com/linagora/tmail/module/LinagoraTestJMAPServerModule.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/WebFingerRoutesContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryWebFingerTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/oidc/WebFingerRoutes.scala

This enable exposing OIDC configuration endpoint
and allows a client to locate the associated
OIDC provider.

ISSUE-326 Implement WebFinger wel known endpoint

---

tmail-backend/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/RateLimitation.scala
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/RateLimitationPlanRepository.scala
tmail-backend/rate-limiter/rate-limiter-api/src/test/scala/com/linagora/tmail/rate/limiter/api/RateLimitationPlanRepositoryContract.scala

ref: https://github.com/linagora/james-project-private/issues/296

ISSUE-296 Implement RateLimitingPlanRepository API and InMemory + contract

---

tmail-backend/mailbox/team-mailboxes/pom.xml
tmail-backend/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/RateLimitingPlanUserRepository.scala
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/memory/MemoryRateLimitingPlanUserRepository.scala
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/model/RateLimitation.scala
tmail-backend/rate-limiter/rate-limiter-api/src/test/scala/com/linagora/tmail/rate/limiter/api/RateLimitingPlanUserRepositoryContract.scala
tmail-backend/rate-limiter/rate-limiter-api/src/test/scala/com/linagora/tmail/rate/limiter/api/memory/MemoryRateLimitingPlanUserRepositoryTest.scala

https://github.com/linagora/james-project-private/issues/303

ISSUE-303 RateLimitingPlanUserRepository API and InMemory + contract

---

tmail-backend/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/RateLimitation.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/pom.xml
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/cassandra/CassandraRateLimitPlanDAO.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/cassandra/CassandraRateLimitPlanTable.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/cassandra/CassandraRateLimitationPlanRepository.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/test/java/com/linagora/tmail/rate/limiter/cassandra/CassandraRateLimitationPlanRepositoryTest.java

Ref https://github.com/linagora/james-project-private/issues/298

ISSUE-298 Implement CassandraRateLimitingPlanRepository

---

tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/CassandraRateLimitationPlanRepository.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/dao/CassandraRateLimitPlanDAO.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/module/CassandraRateLimitingModule.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/table/CassandraRateLimitPlanTable.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/cassandra/CassandraRateLimitationPlanRepository.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/test/java/com/linagora/tmail/rate/limiter/api/cassandra/CassandraRateLimitationPlanRepositoryTest.java

It looks like a rebased mistake before.

ISSUE-298 CassandraRateLimitationPlanRepository::planExists should return java.lang.Boolean instead of scala boolean

---

tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/RateLimitation.scala
tmail-backend/webadmin/webadmin-rate-limit/pom.xml
tmail-backend/webadmin/webadmin-rate-limit/src/main/java/com/linagora/tmail/webadmin/RateLimitPlanUserRoutes.java
tmail-backend/webadmin/webadmin-rate-limit/src/main/java/com/linagora/tmail/webadmin/model/GetAllRateLimitPlanResponseDTO.java
tmail-backend/webadmin/webadmin-rate-limit/src/main/java/com/linagora/tmail/webadmin/model/OperationLimitationsDTO.java
tmail-backend/webadmin/webadmin-rate-limit/src/main/java/com/linagora/tmail/webadmin/model/RateLimitationDTO.java
tmail-backend/webadmin/webadmin-rate-limit/src/main/java/com/linagora/tmail/webadmin/model/RateLimitingPlanCreateRequestDTO.java
tmail-backend/webadmin/webadmin-rate-limit/src/main/java/com/linagora/tmail/webadmin/model/RateLimitingPlanDTO.java
tmail-backend/webadmin/webadmin-rate-limit/src/main/java/com/linagora/tmail/webadmin/model/RateLimitingPlanIdResponse.java
tmail-backend/webadmin/webadmin-rate-limit/src/main/java/com/linagora/tmail/webadmin/model/RateLimitingPlanResetRequestDTO.java
tmail-backend/webadmin/webadmin-rate-limit/src/main/scala/com/linagora/tmail/webadmin/RateLimitPlanManagementRoutes.scala
tmail-backend/webadmin/webadmin-rate-limit/src/test/java/com/linagora/tmail/webadmin/RateLimitPlanManagementRoutesTest.java
tmail-backend/webadmin/webadmin-rate-limit/src/test/java/com/linagora/tmail/webadmin/RateLimitPlanUsersRoutesTest.java

TODO: rebase master, continue implementing.

ISSUE-300 Webadmin API routes for managing the plans

---

tmail-backend/mailets/pom.xml
tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/EnforceRateLimitingPlan.scala
tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/TmailPlanRateLimiter.scala
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/EnforceRateLimitingPlanTest.scala
tmail-backend/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/RateLimitation.scala

ref https://github.com/linagora/james-project-private/issues/299

ISSUE-299 Mailet EnforceRateLimitingPlan implementation

---

tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/EnforceRateLimitingPlan.scala
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/EnforceRateLimitingPlanTest.scala
tmail-backend/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/CacheRateLimitingPlan.scala
tmail-backend/rate-limiter/rate-limiter-api/src/test/scala/com/linagora/tmail/rate/limiter/api/CacheInMemoryRateLimitingPlanRepositoryTest.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/test/java/com/linagora/tmail/rate/limiter/api/cassandra/CacheCassandraRateLimitingPlanRepositoryTest.java

resolve https://github.com/linagora/tmail-backend/issues/344

ISSUE-344 Loading cache abstraction and configuration option for RateLimitingPlan repo

---

Jenkinsfile

This is not working and causes the master build to fail, so I revert it for now

Revert "ISSUE-361: Add trigger for Gatling-imap build"

---

tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContact.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactEventModule.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactListener.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactListenerIntegrationTest.scala

resolve https://github.com/linagora/tmail-backend/issues/364

ISSUE 364 - Set up TMail event bus, event for new contacts, listener to index

---

tmail-backend/mailets/pom.xml
tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/ContactsCollection.scala
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/ContactsCollectionTest.scala

Resolve https://github.com/linagora/tmail-backend/issues/371

ISSUE 371 - Mailet to collect contacts

---

tmail-backend/apps/distributed-es6-backport/pom.xml
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed-es6-backport/src/test/resources/mailetcontainer.xml
tmail-backend/apps/distributed/pom.xml
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/guice/distributed/pom.xml
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/DistributedEmailAddressContactEventModule.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/resources/mailetcontainer.xml
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraContactAutocompleteMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/resources/mailetcontainer.xml
tmail-backend/integration-tests/pom.xml
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/EmailAddressContactInjectKeys.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactEventModule.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/TmailJmapEventSerializer.scala
tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/ContactsCollection.scala
tmail-backend/pom.xml

resolve https://github.com/linagora/tmail-backend/issues/373

ISSUE-373 Auto-complete contact integration test

---

tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/ES6EmailAddressContactSearchEngine.java
tmail-backend/jmap/extensions-es-v6/src/test/java/com/linagora/tmail/james/jmap/model/ES6EmailAddressContactAutoCompleteTest.java
tmail-backend/jmap/extensions-es-v7/pom.xml
tmail-backend/jmap/extensions-es-v7/src/main/java/com/linagora/tmail/james/jmap/ESEmailAddressContactSearchEngine.java
tmail-backend/jmap/extensions-es-v7/src/test/java/com/linagora.tmail.james.jmap.model/ESEmailAddressContactSearchTest.java
tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContact.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactSearchEngineContract.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/MemoryEmailAddressContactSearchEngineTest.scala

Will rebase it against Quan's PR tomorrow to have ES implem as well to take into account and autocomplete case ignore too, but let me know if the API is fine like this though, I wasn't completely sure

Update delete contact

---

docs/modules/ROOT/pages/tmail-backend/features/contactAutocomplete.adoc
docs/modules/ROOT/pages/tmail-backend/features/index.adoc
docs/modules/ROOT/pages/tmail-backend/jmap-extensions/contactAutocomplete.adoc
docs/modules/ROOT/pages/tmail-backend/jmap-extensions/index.adoc
docs/modules/ROOT/pages/tmail-backend/webadmin.adoc

Autocomplete feature doc

---

tmail-backend/apps/distributed-es6-backport/src/main/conf/rabbitmq.properties
tmail-backend/apps/distributed-es6-backport/src/test/java/com/linagora/tmail/james/app/DockerRabbitMQRule.java
tmail-backend/apps/distributed/src/main/conf/rabbitmq.properties
tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/DockerRabbitMQRule.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/contact/RabbitMQEmailAddressContactModule.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraTicketAuthenticationContract.scala
tmail-backend/jmap/extensions-rabbitmq/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EncryptedAttachmentBlobResolver.scala
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedMailboxManager.scala
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedMessageManager.scala
tmail-backend/mailbox/opendistro-tests/src/test/java/org/apache/james/mailbox/opendistro/OpenDistroIntegrationTest.java
tmail-backend/mailbox/opendistro-tests/src/test/java/org/apache/james/mailbox/opendistro/OpenDistroListeningMessageSearchIndexTest.java
tmail-backend/webadmin/webadmin-rate-limit/src/test/java/com/linagora/tmail/webadmin/RateLimitPlanUsersRoutesTest.java

This contains reactive-imap and some perf enhancements. This update should allow easier testing with IMAP on preprod.

Update James-project SHA1

---

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraForwardSetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraForwardSetMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraForwardSetMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/ForwardSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ForwardGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ForwardSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/ForwardSet.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/ForwardSetSerializerTest.scala

Resolve https://github.com/linagora/tmail-backend/issues/420

ISSUE-420 Implement JMAP Forward/Set

---

pom.xml
tmail-backend/apps/distributed-es6-backport/pom.xml
tmail-backend/apps/distributed/pom.xml
tmail-backend/apps/memory/pom.xml

https://github.com/linagora/tmail-backend/issues/410

ISSUE-410 Adopt eclipse-temurin:18-jre-focal docker image

---

tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/cassandra/CassandraBlobIdListDAO.scala
tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/cassandra/CassandraBlobIdListModule.scala
tmail-backend/deployment-tests/common/src/main/java/com/linagora/tmail/deployment/TestContainerWaitStrategy.java
tmail-backend/deployment-tests/distributed-es6-backport/src/test/java/com/linagora/tmail/deployment/TmailDistributedEs6Extension.java
tmail-backend/deployment-tests/distributed-ldap/src/test/java/com/linagora/tmail/deployment/TmailDistributedLdapExtension.java
tmail-backend/deployment-tests/distributed/src/test/java/com/linagora/tmail/deployment/TmailDistributedExtension.java
tmail-backend/deployment-tests/memory/src/test/java/com/linagora/tmail/deployment/TmailMemoryExtension.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedEmailGetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedEmailSetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEmailSendMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEncryptedEmailDetailedViewGetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEncryptedEmailFastViewGetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedMailboxGetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedMailboxSetMethodTest.java
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/longlivedtoken/CassandraLongLivedTokenDAO.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/ticket/CassandraTicketStore.scala
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedMailboxManager.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/CassandraEncryptedEmailDAO.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/CassandraKeystoreDAO.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/DeleteEncryptedProjectionHook.java
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/table/CassandraEncryptedEmailStoreModule.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/table/CassandraKeystoreModule.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/dao/CassandraRateLimitPlanDAO.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/dao/CassandraRateLimitPlanUserDAO.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/table/CassandraRateLimitPlanTable.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/table/CassandraRateLimitPlanUserTable.scala

- Compiling version of Cassandra driver 4 for TMail...
- Also started the distributed app in docker compose!
Needs https://github.com/apache/james-project/pull/599 to be merged...

JAMES-3774 Update to Cassandra driver 4

---

tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/contact/RabbitMQEmailAddressContactModule.java
tmail-backend/jmap/extensions-rabbitmq/src/main/java/com/linagora/tmail/james/jmap/RabbitMQEmailAddressContactConfiguration.java
tmail-backend/jmap/extensions-rabbitmq/src/main/java/com/linagora/tmail/james/jmap/RabbitMQEmailAddressContactSubscriber.java
tmail-backend/jmap/extensions-rabbitmq/src/test/java/com/linagora/tmail/james/jmap/RabbitMQEmailAddressContactConfigurationTest.java

resolve https://github.com/linagora/tmail-backend/issues/449

ISSUE-449 Contact queues and exchanges should manage vhost on rabbitmq

---

Jenkinsfile
tmail-backend/apps/distributed-es6-backport/pom.xml
tmail-backend/apps/distributed/pom.xml
tmail-backend/apps/memory/pom.xml
tmail-backend/deployment-tests/distributed-es6-backport/src/test/java/com/linagora/tmail/deployment/TmailDistributedEs6Extension.java
tmail-backend/deployment-tests/distributed-ldap/src/test/java/com/linagora/tmail/deployment/TmailDistributedLdapExtension.java
tmail-backend/deployment-tests/distributed/src/test/java/com/linagora/tmail/deployment/TmailDistributedExtension.java
tmail-backend/deployment-tests/memory/src/test/java/com/linagora/tmail/deployment/TmailMemoryExtension.java

Avoid Google jib create draft images

---

tmail-backend/integration-tests/smtp/distributed-smtp-integration-tests/pom.xml
tmail-backend/integration-tests/smtp/distributed-smtp-integration-tests/src/test/java/com/linagora/tmail/james/DistributedTeamMailboxSmtpTest.java
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala

resolve https://github.com/linagora/tmail-backend/issues/464

ISSUE-464 fix Error DriverTimeoutException when maven test distributed-smtp-integration-tests

---

tmail-backend/apps/distributed-es6-backport/pom.xml
tmail-backend/apps/distributed/pom.xml
tmail-backend/apps/memory/pom.xml

Java 18 is no longer supported.

ISSUE-477 Update TMail' JRE to 19 version

---

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedJamesConfiguration.java
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedJamesConfiguration.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryConfiguration.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/CombinedUserDAO.java

REQUIRE: wait for merge: https://github.com/apache/james-project/pull/1187

[REFACTORING] List users the reactive way

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesQuotaExtensionsContract.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TMailQuotaRootResolver.scala

resolve https://github.com/linagora/james-project/issues/4631

Issue 4631 quota shared mail boxes

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedFirebaseSubscriptionSetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionSetMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryFirebaseSubscriptionSetMethodTest.java
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebaseCommonModule.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/FirebaseSubscriptionSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseSubscriptionGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseSubscriptionSetCreatePerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseSubscriptionSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/FirebaseSubscription.scala

resolve https://github.com/linagora/tmail-backend/issues/496

ISSUE-496 Implement FirebaseSubscription/set

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/FirebaseSubscriptionSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseSubscriptionSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseSubscriptionSetUpdatePerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/FirebaseSubscription.scala

resolve https://github.com/linagora/tmail-backend/issues/497

ISSUE-497 Implement FirebaseSubscription/set - update (change type)

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionSetMethodContract.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/firebase/CassandraFirebaseSubscriptionDAO.scala
tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebaseCommonModule.java
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebaseConfiguration.java
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebasePushClient.java
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebasePushRequest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/FirebaseSubscriptionSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/FirebaseSubscription.scala
tmail-backend/jmap/extensions/src/test/java/com/linagora/tmail/james/jmap/firebase/FirebaseClientTest.java
tmail-backend/jmap/extensions/src/test/resources/invalid-firebase-private-key.json
tmail-backend/jmap/extensions/src/test/resources/valid-firebase-private-key.json
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/firebase/FirebaseSubscriptionRepositoryContract.scala
tmail-backend/pom.xml

A bit demo of manual tests:
[demo firebase client manual test.webm](https://user-images.githubusercontent.com/55171818/199947515-acf7c5d4-e897-413d-ba99-39b2fb78e2e4.webm)

ISSUE-500 FirebaseClient

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/FirebaseSubscriptionSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseSubscriptionSetUpdatePerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/FirebaseSubscription.scala

resolve https://github.com/linagora/tmail-backend/issues/498

ISSUE-498 Implement FirebaseSubscription/set - update (change expiracy)

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionSetMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryFirebaseSubscriptionGetMethodTest.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryFirebaseSubscriptionSetMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseSubscriptionSetCreatePerformer.scala

resolve https://github.com/linagora/tmail-backend/issues/520

ISSUE-520 FirebaseSubscription/set create should validate firebase token

---

tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/ContactMappingFactory.java
tmail-backend/jmap/extensions-opensearch/src/main/java/com/linagora/tmail/james/jmap/ContactMappingFactory.java
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactSearchEngineContract.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/MemoryEmailAddressContactSearchEngineTest.scala
upgrade-instructions.md

To ASCII characters
rf: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html
TODO: find a way for migration index

ISSUE-534 Autocomplete should support normalizing language-specialized characters when searching

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraForwardSetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraKeystoreSetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraLongLivedTokenSetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLongLivedTokenGetTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraForwardSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraKeystoreSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraLongLivedTokenSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LongLivedTokenGetContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraForwardSetMethodTest.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraKeystoreSetMethodTest.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraLongLivedTokenSetMethodTest.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLongLivedTokenGetTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ForwardSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/KeystoreSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LongLivedTokenGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LongLivedTokenSetMethod.scala

resolve https://github.com/linagora/tmail-backend/issues/530

Issue 530 JMAP endpoint should support being called with accountIds of delegated accounts

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedMailboxManager.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/DeleteEncryptedProjectionHook.java

Reproduce exact the issue on PREPROD and make the contract test more robust.
The tests should fail for now though.
Waiting for the fix: https://github.com/apache/james-project/pull/1447

ISSUE-569 [contract test] Email/query team mailboxes without shares capability should not succeed

---

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraCalendarEventParseMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventParseMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraCalendarEventParseMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventCapabilityFactory.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala

resolve https://github.com/linagora/tmail-backend/issues/564

ISSUE-564 Capability object for JMAP CalendarEvent/parse extension

---

docs/modules/ROOT/pages/tmail-backend/webadmin.adoc
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/probe/JmapGuiceContactAutocompleteProbe.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUsernameChangeIntegrationTest.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/pom.xml
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/UsernameChangeIntegrationContract.java
tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/module/ES6ContactAutoCompleteModule.java
tmail-backend/jmap/extensions-opensearch/src/main/java/com/linagora/tmail/james/jmap/module/OSContactAutoCompleteModule.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/ContactUsernameChangeTaskStep.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContact.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/ContactUsernameChangeTaskStepTest.scala

The code base is ready. I just need to add documentation for it :)

ISSUE-560 Change email addresses contacts

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/calendarEventParsing.adoc
docs/modules/ROOT/pages/tmail-backend/jmap-extensions/index.adoc

Resolve https://github.com/orgs/linagora/projects/2/views/2

ISSUE-561 JMAP specs for calendar event parsing extension

---

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java

waiting for https://github.com/apache/james-project/pull/1474 to be merged...

[FIX] Add missing guice binding for webadmin identity route

---

docs/modules/ROOT/pages/tmail-backend/webadmin.adoc
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUsernameChangeIntegrationTest.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/pom.xml
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/UsernameChangeIntegrationContract.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/probe/RateLimitingProbe.java
tmail-backend/rate-limiter/rate-limiter-api/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/RateLimitingPlanUsernameChangeTaskStep.scala
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/memory/MemoryRateLimitingModule.scala
tmail-backend/rate-limiter/rate-limiter-api/src/test/scala/com/linagora/tmail/rate/limiter/api/RateLimitingPlanUsernameChangeTaskStepTest.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/module/CassandraRateLimitingModule.scala

MOB result of this morning session.
Missing:

ISSUE-610 Changing username: migrate rate limiting plan

---

demo/krakend/krakend.json

[OIDC] Add Linagora services discovery route to KrakenD

---

tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailbox.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TeamMailboxRepositoryContract.scala

Resolve https://github.com/linagora/tmail-backend/issues/657

ISSUE-657 Create more default mailboxes when add a new team-mailbox

---

demo/apisix/conf/apisix.yaml

Rate limiting apisix

---

demo/apisix/conf/apisix.yaml

resolve: https://github.com/linagora/tmail-backend/issues/643

ISSUE-643 [APISIX] Add circuit breaker plugin

---

demo/apisix/conf/apisix.yaml
demo/tmail/jmap.properties

[demo apisix websocket.webm](https://user-images.githubusercontent.com/55171818/234822654-4c01ade5-381c-44b5-8c2d-120d7a1f5fc2.webm)

ISSUE-646 Add JMAP websocket endpoint

---

demo/apisix/conf/apisix.yaml
demo/docker-compose.yml
demo/tmail/usersrepository.xml

[demo basic auth endpoints APISIX.webm](https://user-images.githubusercontent.com/55171818/235109234-6495cd53-099c-4ed2-a2e9-2a3c36763ef3.webm)

ISSUE-645 Add basic authentication routes to APISIX

---

demo/apisix/Dockerfile
demo/apisix/conf/apisix.yaml
demo/apisix/conf/config.yaml
demo/apisix/tmail-apisix-plugin-runner/README.md
demo/apisix/tmail-apisix-plugin-runner/pom.xml
demo/apisix/tmail-apisix-plugin-runner/src/main/java/META-INF/MANIFEST.MF
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/AppConfiguration.java
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/ChannelLogoutController.java
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/IRevokedTokenRepository.java
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/RedisRevokedTokenRepository.java
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/TmailApisixPluginRunnerApplication.java
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/TokenRevokedFilter.java
demo/apisix/tmail-apisix-plugin-runner/src/main/resources/application.yaml
demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/ClusterRedisRevokedTokenRepositoryTest.java
demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/RedisRevokedTokenRepositoryTest.java
demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/RevokedTokenRepositoryContract.java
demo/apisix/tmail-apisix-plugin-runner/src/test/resources/fix_partition.sh
demo/apisix/tmail-apisix-plugin-runner/src/test/resources/redis-overrides.conf
demo/dev.sh
demo/docker-compose.yml
demo/lemonldap/lmConf-1.json
demo/test.sh

resolve https://github.com/linagora/james-project-private/issues/624

ISSUE-624 Apisix - SLO

---

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEmailRecoveryActionSetMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/resources/jmap.properties
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EmailRecoveryActionSetMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryEmailRecoveryActionSetMethodTest.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/resources/jmap.properties
tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/EmailRecoveryActionSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/json.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EmailRecoveryActionSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/MessageVaultCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EmailRecoveryAction.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/EmailRecoveryActionSerializerTest.scala

resolve https://github.com/linagora/tmail-backend/issues/678

ISSUE-678 JMAP - EmailRecoveryAction/set create

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/deletedMessagesVault.adoc
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEmailRecoveryActionGetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EmailRecoveryActionGetMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryEmailRecoveryActionGetMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/EmailRecoveryActionSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EmailRecoveryActionGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EmailRecoveryActionSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EmailRecoveryAction.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/EmailRecoveryActionSerializerTest.scala

Start with the specification modification first, following: https://github.com/linagora/tmail-backend/issues/680#issuecomment-1560435052

ISSUE-680 EmailRecoveryAction/get

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEmailRecoveryActionSetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/pom.xml
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EmailRecoveryActionSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/EmailRecoveryActionSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EmailRecoveryActionSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EmailRecoveryAction.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/EmailRecoveryActionSerializerTest.scala

resolve https://github.com/linagora/tmail-backend/issues/681

ISSUE-681 EmailRecoveryAction/set update

---

docs/modules/ROOT/pages/tmail-backend/webadmin.adoc
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUserDeletionIntegrationTest.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/UserDeletionIntegrationContract.java
tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/PGPKeysUserDeletionTaskStep.scala
tmail-backend/mailbox/encrypted/api/src/test/scala/com/linagora/tmail/encrypted/PGPKeysUserDeletionTaskStepContract.scala
tmail-backend/mailbox/encrypted/cassandra/src/main/java/com/linagora/tmail/encrypted/cassandra/CassandraKeystoreManager.scala
tmail-backend/mailbox/encrypted/memory/src/main/java/com/linagora/tmail/encrypted/InMemoryKeystoreManager.scala
tmail-backend/mailbox/encrypted/memory/src/test/java/com/linagora/tmail/encrypted/MemoryPGPKeysUserDeletionTaskStepTest.java

resolve https://github.com/linagora/tmail-backend/issues/667

ISSUE-667 PGP public keys deletion

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/pom.xml
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEmailRecoveryActionIntegrationTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EmailRecoveryActionIntegrationTest.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEchoMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/pom.xml
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryEmailRecoveryActionIntegrationTest.java

resolve https://github.com/linagora/tmail-backend/issues/679

ISSUE-679 [Deleted message vault] JMAP - Guice bindings + Integration tests

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/Label.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/label/LabelRepositoryContract.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/label/MemoryLabelRepositoryTest.scala

resolve https://github.com/linagora/tmail-backend/issues/703

ISSUE-703 LabelRepository memory implementation

---

tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelDAO.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelRepository.scala
tmail-backend/jmap/extensions-cassandra/src/test/java/com/linagora/tmail/james/jmap/label/CassandraLabelRepositoryTest.java

resolve https://github.com/linagora/tmail-backend/issues/704

ISSUE-704 Cassandra implementation of LabelRepository

---

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraLabelGetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/module/JmapGuiceLabelModule.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/probe/JmapGuiceLabelProbe.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraLabelGetMethodTest.java
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/LabelSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/Label.scala

ISSUE-707 Label/get method

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelSetDeletePerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/LabelSet.scala

ISSUE-716 Label/set destroy

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelChangeRepository.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/label/LabelChangeRepositoryContract.scala

resolve https://github.com/linagora/tmail-backend/issues/714

ISSUE-714 Implement LabelChangeRepository + memory impl + contract test

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/LabelSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelSetUpdatePerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/LabelSet.scala

ISSUE-709 Label/set update

---

tmail-backend/jmap/extensions-cassandra/pom.xml
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelChangeDAO.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelChangeRepository.scala
tmail-backend/jmap/extensions-cassandra/src/test/java/com/linagora/tmail/james/jmap/label/CassandraLabelChangeRepositoryTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelChangeRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/Label.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/label/LabelChangeRepositoryContract.scala

ISSUE-715 Cassandra implementation for LabelChangeRepository

---

docs/modules/ROOT/pages/tmail-backend/webadmin.adoc
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUserDeletionIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUsernameChangeIntegrationTest.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/UserDeletionIntegrationContract.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/UsernameChangeIntegrationContract.java
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelDAO.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelUserDeletionTaskStep.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelUsernameChangeTaskStep.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/label/LabelRepositoryContract.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/label/LabelUserDeletionTaskStepTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/label/LabelUsernameChangeTaskStepTest.scala

ISSUE-722 Labels username change + user deletion

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraLabelChangesMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/pom.xml
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelChangesMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/probe/JmapGuiceLabelProbe.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraLabelChangesMethodTest.java
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelChangeRepository.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/label/CassandraLabelRepository.scala
tmail-backend/jmap/extensions-cassandra/src/test/java/com/linagora/tmail/james/jmap/label/CassandraLabelChangeRepositoryTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/LabelChangesSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelChangeRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelChangesPopulate.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelChangesMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelSetCreatePerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelSetDeletePerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelSetUpdatePerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/Label.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/LabelChange.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/LabelChangesSerializerTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/label/LabelChangeRepositoryContract.scala
tmail-backend/pom.xml

resolve https://github.com/linagora/tmail-backend/issues/710
resolve https://github.com/linagora/tmail-backend/issues/718

ISSUE-710 Label/change JMAP method

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxRevokeAccessMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailCanSendFromTest.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailQuotaRootResolverTest.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TeamMailboxRepositoryContract.scala
tmail-backend/mailets/src/test/java/com/linagora/tmail/mailet/LinagoraMailetContextTest.java
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/TMailMailboxAppenderTest.scala
tmail-backend/smtp-extensions/src/test/java/com/linagora/tmail/smtp/TMailValidRcptHandlerTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/RecomputeQuotaTeamMailboxesRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/TeamMailboxQuotaRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/UserTeamMailboxRoutesTest.java

resolve https://github.com/linagora/tmail-backend/issues/740

ISSUE_740 Subscribe members to the team mailboxes

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/pushWithFirebase.adoc
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraLabelChangesMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelChangesMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/package.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraLabelChangesMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelChangeRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/label/LabelChangesPopulate.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelGetMethod.scala

resolve https://github.com/linagora/tmail-backend/issues/717

Issue 717 push for label changes

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxAutocompleteCallback.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxJmapModule.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxCallback.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailCanSendFromTest.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailQuotaRootResolverTest.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TeamMailboxRepositoryContract.scala
tmail-backend/mailets/pom.xml
tmail-backend/mailets/src/test/java/com/linagora/tmail/mailet/LinagoraMailetContextTest.java
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/TMailMailboxAppenderTest.scala
tmail-backend/pom.xml
tmail-backend/smtp-extensions/pom.xml
tmail-backend/smtp-extensions/src/test/java/com/linagora/tmail/smtp/TMailValidRcptHandlerTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/pom.xml
tmail-backend/webadmin/webadmin-team-mailboxes/src/main/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutes.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/RecomputeQuotaTeamMailboxesRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/TeamMailboxQuotaRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/UserTeamMailboxRoutesTest.java

ISSUE-741 Auto-complete for team mailboxes

---

tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/ES6EmailAddressContactSearchEngine.java
tmail-backend/jmap/extensions-opensearch/src/main/java/com/linagora/tmail/james/jmap/OSEmailAddressContactSearchEngine.java
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactSearchEngineContract.scala

resolve https://github.com/linagora/tmail-backend/issues/758

ISSUE-758 Fix Auto complete - query only email field when input has atSign

---

tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/rspamd/RspamdModule.java
tmail-backend/integration-tests/healthcheck/distributed-healthcheck-integration-tests/pom.xml
tmail-backend/integration-tests/healthcheck/distributed-healthcheck-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedTMailHealthCheckIntegrationTests.java
tmail-backend/integration-tests/healthcheck/healthcheck-integration-tests-common/src/main/java/com/linagora/tmail/integration/TMailHealthCheckIntegrationTests.java

ISSUE-762 Integrate Rspamd Healthcheck

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettings.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepository.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepositoryContract.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/MemoryJmapSettingsRepositoryTest.scala

resolve https://github.com/linagora/tmail-backend/issues/785

ISSUE-785 JMAPSettingRepository api interface + Inmemory implement + Test contract and memory tests

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/jmapSettings.adoc
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/firebase/FirebasePushEnableSetting.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/firebase/FirebasePushListener.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/JmapSettingsSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/JmapSettingsGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/JmapSettingsGet.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettings.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/firebase/FirebasePushEnableSettingParserTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/firebase/FirebasePushListenerTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/JmapSettingsSerializerTest.scala

resolve https://github.com/linagora/tmail-backend/issues/788

ISSUE-788 Setting to enable Push for firebase

---

Jenkinsfile
pom.xml
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedJamesConfiguration.java
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedJamesConfiguration.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/backend-commons/elasticsearch-v6/pom.xml
tmail-backend/integration-tests/healthcheck/distributed-healthcheck-integration-tests/pom.xml
tmail-backend/integration-tests/healthcheck/distributed-healthcheck-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedTMailHealthCheckIntegrationTests.java
tmail-backend/integration-tests/healthcheck/healthcheck-integration-tests-common/src/main/java/com/linagora/tmail/integration/TMailHealthCheckIntegrationTests.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/pom.xml
tmail-backend/integration-tests/rate-limiter/distributed-rate-limiter-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedRateLimitingPlanIntegrationTest.java
tmail-backend/integration-tests/rspamd/rspamd-integration-tests-common/src/main/java/com/linagora/tmail/integration/RspamdScannerIntegrationContract.java
tmail-backend/integration-tests/smtp/distributed-smtp-integration-tests/pom.xml

resolve https://github.com/linagora/tmail-backend/issues/795

ISSUE-795 Distributed server should be able to start when missing redis configuration file

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/JmapSettingsGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/JmapSettingsSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/probe/JmapSettingsProbe.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryJmapSettingsGetMethodTest.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryJmapSettingsSetMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/JmapSettingsSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/JmapSettingsGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/JmapSettingsSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/JmapSettingsSet.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettings.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepository.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/JmapSettingsSerializerTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepositoryContract.scala

resolve https://github.com/linagora/tmail-backend/issues/782

ISSUE-782 Implement JMAP method Settings/set update (full reset)

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepository.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepositoryContract.scala

ISSUE-785 Add JmapSettingsRepository delete API

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraFilterSetMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/JmapSettingsSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraFilterSetMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryJmapSettingsSetMethodTest.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraFilterSetMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FilterSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/JmapSettingsGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/JmapSettingsSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettings.scala

resolve #787 
TODO check someplace are seem to always push StateChangeEvent even no successful change e.g `FilterSetMethod`

ISSUE-787 Push for Settings

---

docs/modules/ROOT/pages/tmail-backend/webadmin.adoc
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/probe/JmapSettingsProbe.scala
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUserDeletionIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUsernameChangeIntegrationTest.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/UserDeletionIntegrationContract.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/UsernameChangeIntegrationContract.java
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/settings/CassandraJmapSettingsRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsUserDeletionTaskStep.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsUsernameChangeTaskStep.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsUserDeletionTaskStepTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsUsernameChangeTaskStepTest.scala

ISSUE-780 Settings: User rename + User deletion

---

dockerfiles/jenkins-runner/Dockerfile

Updates packages for bugs and security and better clean to reduce docker image size

Securize and reduce docker image

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/probe/JmapSettingsProbe.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/settings/CassandraJmapSettingsDAO.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/firebase/FirebasePushEnableSetting.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/JmapSettingsSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/JmapSettingsGet.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/JmapSettingsSet.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettings.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepository.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/firebase/FirebasePushEnableSettingParserTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/firebase/FirebasePushListenerTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/JmapSettingsSerializerTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepositoryContract.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsUserDeletionTaskStepTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsUsernameChangeTaskStepTest.scala

- Easier when using in java code
resolve https://github.com/linagora/tmail-backend/pull/829#issuecomment-1744189027

ISSUE-785 Moving JmapSettingsKey, JmapSettingsValue to outside the parent object JmapSettings

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/jmapSettings.adoc
docs/modules/ROOT/pages/tmail-backend/webadmin.adoc
tmail-backend/apps/distributed-es6-backport/pom.xml
tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/distributed/pom.xml
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/pom.xml
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedCleanupTrashIntegrationContract.java
tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/CleanupTrashIntegrationContract.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/settings/JmapSettings.scala
tmail-backend/pom.xml
tmail-backend/webadmin/webadmin-mailbox/pom.xml
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/CleanupContext.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/CleanupTaskDetails.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/CleanupTrashService.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/CleanupTrashTask.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/CleanupTrashTaskAdditionalInformationDTO.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/CleanupTrashTaskDTO.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/CleanupTrashTaskRegistration.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/MailboxesCleanupModule.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/RunningOptions.java
tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/cleanup/RunningOptionsDTO.java
tmail-backend/webadmin/webadmin-mailbox/src/test/java/com/linagora/tmail/webadmin/cleanup/CleanupTrashServiceTest.java
tmail-backend/webadmin/webadmin-mailbox/src/test/java/com/linagora/tmail/webadmin/cleanup/CleanupTrashTaskSerializationTest.java

Basic structure for this function

ISSUE-821 Webadmin task for trash cleanup

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ForwardSetMethod.scala
tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/TmailLocalDelivery.scala

resolve https://github.com/linagora/tmail-backend/issues/833

ISSUE-833 Audit trail

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraFilterSetMethodContract.scala

Needs https://github.com/apache/james-project/pull/1744

Fix rule filter actions

---

tmail-backend/webadmin/webadmin-mailbox/src/main/java/com/linagora/tmail/webadmin/archival/InboxArchivalService.java

With 30 users enabled on preprod.
Before: Preprod was blown up after 20 minutes runtime with multiple `CassandraTimeoutException`.
After: Preprod was fine with no error logs.
```json
{
"additionalInformation": {
"type": "InboxArchivalTask",
"timestamp": "2023-10-11T06:40:48.045723776Z",
"successfulUsersCount": 30,
"failedUsersCount": 0,
"failedUsers": [],
"archivedMessageCount": 83833,
"errorMessageCount": 0
},
"type": "InboxArchivalTask",
"submittedFrom": "tmail-imap-smtp-5997867cb9-sjqvt",
"executedOn": "tmail-jmap-7c47449bb8-kz7tp",
"cancelledFrom": null,
"submitDate": "2023-10-11T06:16:31.774+0000",
"status": "completed",
"taskId": "a0b4831d-fded-4c24-9553-93531296c002",
"completedDate": "2023-10-11T06:40:48.067+0000",
"startedDate": "2023-10-11T06:16:32.719+0000"
}
```
The task took …

INBOX archival: reduce concurrency level

---

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc

resolve https://github.com/linagora/tmail-backend/issues/843

ISSUE-843 Document firebase setup

---

tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebasePushClient.java

Was needed by mobile team to handle Notification Service Extension (an extension to modify notification of iOS)
cc @dab246

ISSUE-870 Enable mutable-content for APNS notification

---

tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebasePushClient.java

Needed to be able to modify the notification message on iOS side.
cc @dab246

[FCM] Set alert for the APN message

---

tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebasePushClient.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/firebase/FirebasePushListener.scala

resolve https://github.com/linagora/tmail-backend/issues/889
cc @dab246 please review.
Working on deploying this on preprod BTW.

[FCM] Only set alert for the APN message upon EmailDelivery

---

Jenkinsfile

resolve: https://github.com/linagora/tmail-backend/issues/903
not sure if it works or not
Just tried with Jib document 
https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage

ISSUE-903 [CI build] Postgres experimental branch pushes also postgres image to docker hub on latest tag

---

tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala

Before: Manipulating team mailboxes via webadmin (after first few requests) leads to webadmin hanging issue + RabbitMQ consumers crash.
After: Manipulating team mailboxes via webadmin using multiple consecutive requests is just fine.

[FIX] TeamMailboxRepository: avoid executing code on boundedElastic at best

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/mail/Mailbox.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/mail/TMailMailboxSortOrderProviderModule.scala

cf: https://github.com/linagora/tmail-flutter/issues/2328

Move Sent mailbox to a higher sort order

---

tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/EncryptedDistributedServerTest.java
tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/BlobStoreModulesChooser.java
tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/SingleSaveBlobStoreDAO.java
tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/SingleSaveBlobStoreModule.java

resolve https://github.com/linagora/tmail-backend/issues/929

ISSUE-929 Fix blob store module chooser

---

demo/apisix/conf/config.yaml
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/RewriteXUserFilter.java
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/TokenRevokedFilter.java
demo/apisix/tmail-apisix-plugin-runner/src/main/resources/application-prod.yaml

resolve https://github.com/linagora/tmail-backend/issues/935

ISSUE-640 Apisix - change log level of plugin runner for prod profile

---

tmail-backend/jmap/extensions-postgres/pom.xml
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/firebase/PostgresFirebaseModule.java
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/firebase/PostgresFirebaseSubscriptionDAO.java
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/firebase/PostgresFirebaseSubscriptionRepository.java
tmail-backend/jmap/extensions-postgres/src/test/java/com/linagora/tmail/james/jmap/firebase/PostgresFirebaseSubscriptionRepositoryTest.java
tmail-backend/pom.xml

resolve https://github.com/linagora/tmail-backend/issues/910

ISSUE-910 Implement PostgresFirebaseSubscriptionRepository

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventParse.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventReplyGenerator.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventParsedTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventReplyGeneratorTest.scala

resolve https://github.com/linagora/tmail-backend/issues/949

ISSUE-949 [ICS Reply] ICS patching core process

---

tmail-backend/apps/postgres/pom.xml
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/jmap/extensions-postgres/pom.xml
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/firebase/PostgresFirebaseModule.java
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/firebase/PostgresFirebaseRepositoryModule.java
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/label/PostgresLabelDAO.java
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/label/PostgresLabelModule.java
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/label/PostgresLabelRepository.java
tmail-backend/jmap/extensions-postgres/src/main/java/com/linagora/tmail/james/jmap/label/PostgresLabelRepositoryModule.java
tmail-backend/jmap/extensions-postgres/src/main/scala/com/linagora/tmail/james/jmap/label/PostgresLabelDAOUtils.scala
tmail-backend/jmap/extensions-postgres/src/test/java/com/linagora/tmail/james/jmap/label/PostgresLabelRepositoryTest.java

resolve https://github.com/linagora/tmail-backend/issues/912

ISSUE-912 Implement PostgresLabelRepository

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraCalendarEventMaybeMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventMaybeMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraCalendarEventMaybeMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/CalendarEventReplySerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventMaybeMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventParseMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventReply.scala

resolve https://github.com/linagora/tmail-backend/issues/952

ISSUE-952 [ICS Reply] CalendarEvent/maybe JMAP method

---

tmail-backend/apps/postgres/pom.xml
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/pom.xml
tmail-backend/rate-limiter/rate-limiter-api/src/test/scala/com/linagora/tmail/rate/limiter/api/RateLimitingPlanUserRepositoryContract.scala
tmail-backend/rate-limiter/rate-limiter-postgres/pom.xml
tmail-backend/rate-limiter/rate-limiter-postgres/src/main/scala/com/linagora/tmail/rate/limiter/api/postgres/dao/PostgresRateLimitPlanUserDAO.scala
tmail-backend/rate-limiter/rate-limiter-postgres/src/main/scala/com/linagora/tmail/rate/limiter/api/postgres/module/PostgresRateLimitingModule.scala
tmail-backend/rate-limiter/rate-limiter-postgres/src/main/scala/com/linagora/tmail/rate/limiter/api/postgres/repository/PostgresRateLimitingPlanUserRepository.scala
tmail-backend/rate-limiter/rate-limiter-postgres/src/main/scala/com/linagora/tmail/rate/limiter/api/postgres/table/PostgresRateLimitPlanUserTable.scala
tmail-backend/rate-limiter/rate-limiter-postgres/src/test/java/com/linagora/tmail/rate/limiter/api/postgres/PostgresRateLimitingPlanUserRepositoryTest.java

resolve https://github.com/linagora/tmail-backend/issues/915

ISSUE-915 Implement PostgresRateLimitingPlanUserRepository

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/calendarEventReply.adoc
docs/modules/ROOT/pages/tmail-backend/jmap-extensions/index.adoc

resolve https://github.com/linagora/tmail-backend/issues/967

ISSUE-953 [ICS Reply] Documentation

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventAcceptMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventMaybeMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventRejectMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventReplyGenerator.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventReplyGeneratorTest.scala

resolve https://github.com/linagora/tmail-backend/issues/975

ISSUE-975 Reply ICS should generate new DTSTAMP / LAST-MODIFIED

---

Jenkinsfile
pom.xml

Let's see the `jdk17` CI node complains first...

Upgrade JDK to 21

---

tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryMailboxSetMethodTest.java

Rebase on james/postgresql branch for tmail pg app

Update James SHA-1 (pg-app)

---

tmail-backend/apps/postgres/docker-compose-distributed.yml
tmail-backend/apps/postgres/docker-compose.yml
tmail-backend/apps/postgres/pom.xml
tmail-backend/apps/postgres/sample-configuration/jmap.properties
tmail-backend/apps/postgres/sample-configuration/mailetcontainer.xml
tmail-backend/apps/postgres/src/main/eml-template/calendar_reply_accepted-en.eml
tmail-backend/apps/postgres/src/main/eml-template/calendar_reply_accepted-fr.eml
tmail-backend/apps/postgres/src/main/eml-template/calendar_reply_declined-en.eml
tmail-backend/apps/postgres/src/main/eml-template/calendar_reply_declined-fr.eml
tmail-backend/apps/postgres/src/main/eml-template/calendar_reply_tentative-en.eml
tmail-backend/apps/postgres/src/main/eml-template/calendar_reply_tentative-fr.eml
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/apps/postgres/src/test/java/com/linagora/tmail/james/app/CombinedIdentityTmailServerTest.java
tmail-backend/apps/postgres/src/test/java/com/linagora/tmail/james/app/DistributedPostgresTmailServerTest.java
tmail-backend/integration-tests/healthcheck/postgres-healthcheck-integration-tests/pom.xml
tmail-backend/integration-tests/healthcheck/postgres-healthcheck-integration-tests/src/test/java/com/linagora/tmail/integration/postgres/PostgresTMailHealthCheckIntegrationTests.java
tmail-backend/integration-tests/healthcheck/postgres-healthcheck-integration-tests/src/test/resources/mailetcontainer.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/TMailJMAPModule.scala

resolve https://github.com/linagora/tmail-backend/issues/981

Update James SHA-1 (postgresql)

---

tmail-backend/apps/postgres/pom.xml
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/apps/postgres/src/test/java/com/linagora/tmail/james/app/DistributedPostgresTmailServerTest.java
tmail-backend/integration-tests/healthcheck/postgres-healthcheck-integration-tests/src/test/java/com/linagora/tmail/integration/postgres/PostgresTMailHealthCheckIntegrationTests.java

@vttranlina it's a bit dirty but feel free to have a look.

Missing bindings for tmail pg-app

---

Jenkinsfile

According to https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#interpolation-of-sensitive-environment-variables

[CI] String interpolation of sensitive env variable in Jenkins pipeline

---

pom.xml

Java 22 seems to have some minor Garbage Collection improvements: https://www.oracle.com/java/technologies/javase/22-relnote-issues.html

Upgrade JRE to 22

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventParseMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventReplyPerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventParse.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventReplyGenerator.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventParsedTest.scala

resolve https://github.com/linagora/tmail-backend/issues/1006

ISSUE-1006 Fix CalendarEvent reply extension throw serverFail error

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedEmailAddressContactEventDeadLettersModule.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/DistributedEmailAddressContactEventModule.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/RabbitMQAndRedisEventBusModule.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactListener.scala

resolve: https://github.com/linagora/james-project-private/issues/788
Merge requirement: [james-project] https://github.com/apache/james-project/pull/2205

ISSUE-986 Fixup guice binding EventDeadLetter for AUTOCOMPLETE EventBus

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedEmailAddressContactEventDeadLettersModule.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresEmailAddressContactEventDeadLettersModule.java
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/DistributedEmailAddressContactEventModule.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactListener.scala

resolve: https://github.com/linagora/james-project-private/issues/788

ISSUE-986 Fixup guice binding EventDeadLetter for AUTOCOMPLETE EventBus (postgresql)

---

tmail-backend/jmap/extensions/pom.xml
tmail-backend/mailbox/encrypted/pgp-utils/pom.xml
tmail-backend/mailbox/encrypted/pgp-utils/src/test/java/com/linagora/tmail/pgp/Decrypter.java
tmail-backend/pom.xml

resolve https://github.com/linagora/tmail-backend/issues/959

ISSUE-599 Upgrade bouncycastle to match James version => 1.77

---

tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/CleanRedisEventBusService.java
tmail-backend/event-bus-redis/src/main/scala/org/apache/james/events/RedisEventBusClientFactory.scala
tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/CleanRedisEventBusServiceTest.java
tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RedisPlaygroundTest.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/RabbitMQAndRedisEventBusModule.java

ISSUE-941 Clean redis event bus upon james crash

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventReplyPerformer.scala

resolve https://github.com/linagora/tmail-backend/issues/1020

ISSUE-1020 Fix Leak resource at CalendarEventReplyPerformer

---

demo/apisix/tmail-apisix-plugin-runner/README.md
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/AppConfiguration.java
demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/RedisRevokedTokenRepository.java
demo/apisix/tmail-apisix-plugin-runner/src/main/resources/application.yaml
demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/ClusterRedisRevokedTokenRepositoryTest.java
demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/ContainerHelper.java
demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/RedisRevokedTokenRepositoryTest.java

Resolve: https://github.com/linagora/tmail-backend/issues/1023

ISSUE-1023 Apisix plugin - support case Redis down

---

tmail-backend/apps/distributed/src/main/conf/redis.properties
tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RabbitMQAndRedisEventBus.java
tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RedisEventBusConfiguration.java
tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RedisKeyRegistrationHandler.java
tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/TMailEventDispatcher.java
tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/CleanRedisEventBusServiceTest.java
tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusTest.java
tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RedisEventBusServiceTest.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/RabbitMQAndRedisEventBusModule.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraRedisFailureTest.java

- Support configuration for failure ignore when pub/sub by Redis.
- timeout for redis event bus operations
resolve https://github.com/linagora/james-project/issues/5175

ISSUE-1024 JMAP - fault tolerance when Redis down

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java

- Ref: https://github.com/linagora/james-project/issues/5180

Fixup guice binding for RedisHealthCheck

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventReplyPerformer.scala

[ENHANCEMENT] Avoid copy of the mime message in calendar replies

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/jmap/extensions-cassandra/pom.xml
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/CassandraPublicAssetDAO.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/CassandraPublicAssetRepository.scala
tmail-backend/jmap/extensions-cassandra/src/test/java/com/linagora/tmail/james/jmap/publicAsset/CassandraPublicAssetRepositoryTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetStorage.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetsModule.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetRepositoryContract.scala

resolve https://github.com/linagora/tmail-backend/issues/1040

ISSUE-1040 Implement CassandraPublicAssetRepository

---

docs/modules/ROOT/pages/tmail-backend/features/index.adoc

I am not sure what else to document...

ISSUE-1047 Document the PublicAsset feature

---

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/apps/postgres/sample-configuration/jmap.properties
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/guice/protocols/jmap/src/test/java/com/linagora/tmail/module/LinagoraTestJMAPServerModule.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraEchoMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEchoMethodContract.scala
tmail-backend/jmap/extensions-cassandra/pom.xml
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/CassandraPublicAssetDAO.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/CassandraPublicAssetRepository.scala
tmail-backend/jmap/extensions-cassandra/src/test/java/com/linagora/tmail/james/jmap/publicAsset/CassandraPublicAssetRepositoryTest.java
tmail-backend/jmap/extensions-postgres/pom.xml
tmail-backend/jmap/extensions-postgres/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PostgresPublicAssetDAO.scala
tmail-backend/jmap/extensions-postgres/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PostgresPublicAssetRepository.scala
tmail-backend/jmap/extensions-postgres/src/test/java/com/linagora/tmail/james/jmap/publicAsset/PostgresPublicAssetRepositoryTest.java
tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/PublicAssetsCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetBlobReferenceSource.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetStorage.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetsModule.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/publicAsset/MemoryPublicAssetRepositoryTest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetRepositoryContract.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetURITest.scala

resolve #1041 
Please skip the first 3 cherry-pick commits (to get the needed interface and module).

ISSUE-1041 Implement PostgresPublicAssetRepository

---

demo/apisix/conf/apisix.yaml

https://github.com/linagora/tmail-backend/assets/55171818/9e35f3da-5658-42df-9521-070c209258b6

ISSUE-1046 APISIX route for public asset

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/PublicAssetSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/PublicAssetSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetSetRequest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/PublicAssetSerializerTest.scala

resolve https://github.com/linagora/tmail-backend/issues/1049

ISSUE-1049 [PublicAsset] PublicAsset/set destroy JMAP method

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/PublicAssetGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/PublicAssetSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/PublicAssetSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/PublicAssetGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/PublicAssetGetRequest.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetSetRequest.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/PublicAssetSerializerTest.scala

resolve https://github.com/linagora/tmail-backend/issues/1074

ISSUE-1074 [PublicAsset] refactor identityIds handling with PublicAsset/get and /set create methods

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/calendarEventReply.adoc

ISSUE-1080 Update calendarEventReply.adoc

---

tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/RabbitMQAndRedisEventBusModule.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventReplyPerformer.scala

ISSUE-1093 Revert "[ENHANCEMENT] Avoid copy of the mime message in calendar replies"

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/pom.xml
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EmailRecoveryActionGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EmailRecoveryActionSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebasePushContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/JmapSettingsGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/JmapSettingsSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelChangesMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventAcceptMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventParseMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraContactAutocompleteMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEmailSendMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEncryptedEmailDetailedViewGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEncryptedEmailFastViewGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraFilterGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraFilterSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraFilterStateChangeTest.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraForwardGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraForwardSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraKeystoreGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraKeystoreSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/PublicAssetGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/PublicAssetSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxRevokeAccessMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala

resolve https://github.com/linagora/tmail-backend/issues/1095

ISSUE-1095 More @BasicFeature JMAP integration tests

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/jmapTeamMailboxMembers.adoc

ISSUE-1085 JMAP specs for JMAP TeamMailboxMember extension

---

pom.xml
tmail-backend/apps/memory/pom.xml
tmail-backend/deployment-tests/memory/pom.xml
tmail-backend/integration-tests/smtp/distributed-smtp-integration-tests/pom.xml

- Do it after migrated james to java 21

[MAVEN] Upgrade Maven plugins

---

tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailbox.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxProbe.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailCanSendFromTest.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TeamMailboxRepositoryContract.scala
tmail-backend/smtp-extensions/src/test/java/com/linagora/tmail/smtp/TMailValidRcptHandlerTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/main/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutes.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/UserTeamMailboxRoutesTest.java

ISSUE-1087 Add member role to TeamMailboxRepository

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebasePushContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/FirebaseSubscriptionSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelChangesMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventAcceptMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventMaybeMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventParseMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventRejectMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventReplyWithAMQPWorkflowContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraContactAutocompleteMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraFilterGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraFilterSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraForwardGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraKeystoreGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraKeystoreSetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/PublicAssetGetMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesQuotaExtensionsContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetRoutes.scala
tmail-backend/pom.xml
tmail-backend/webadmin/webadmin-email-address-contact/src/test/java/com/linagora/tmail/webadmin/EmailAddressContactRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutesTest.java

The update james sha-1 for getting the lib updates has been missing and a few libs too also.
Thinking we could potentially upgrade bouncycastle as well while we are at it (latest version is 1.78.1), but needs to be done on james side first.

Update James SHA-1

---

tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailConfiguration.java
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/blob/blobid-list/src/test/java/com/linagora/tmail/blob/blobid/list/postgres/PostgresSingleSaveBlobStoreTest.java
tmail-backend/jmap/extensions-postgres/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PostgresPublicAssetRepository.scala
tmail-backend/jmap/extensions-postgres/src/test/java/com/linagora/tmail/james/jmap/publicAsset/PostgresPublicAssetRepositoryTest.java
tmail-backend/jmap/extensions-postgres/src/test/java/com/linagora/tmail/james/jmap/settings/PostgresJmapSettingsRepositoryTest.java
tmail-backend/mailbox/encrypted/mailbox-encrypted-postgres/src/test/java/com/linagora/tmail/encrypted/postgres/PostgresEncryptedEmailContentStoreTest.java
tmail-backend/rate-limiter/rate-limiter-postgres/src/main/scala/com/linagora/tmail/rate/limiter/api/postgres/repository/PostgresRateLimitingPlanUserRepository.scala
tmail-backend/rate-limiter/rate-limiter-postgres/src/test/java/com/linagora/tmail/rate/limiter/api/postgres/PostgresRateLimitingPlanRepositoryTest.java
tmail-backend/rate-limiter/rate-limiter-postgres/src/test/java/com/linagora/tmail/rate/limiter/api/postgres/PostgresRateLimitingPlanUserRepositoryTest.java

Update tmail to adapt https://github.com/apache/james-project/pull/2296

Add rls support postgres mailbox module in case rls is enabled

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventAcceptMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventReplyGenerator.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventReplyGeneratorTest.scala

resolve https://github.com/linagora/tmail-backend/issues/1121

ISSUE-1121 CalendarEvent reply: Fix issue: can not reply when user isinvited via mailing list

---

demo/docker-compose.yml
demo/ldap/populate.ldif
demo/tmail/domainlist.xml
demo/tmail/mailetcontainer.xml
demo/tmail/smtpserver.xml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/tmail-backend/features/ldapMailingLists.adoc
tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/CombinedUsersRepositoryModule.java
tmail-backend/combined-identity/src/test/java/com/linagora/tmail/combined/identity/CombinedUsersRepositoryTest.java
tmail-backend/mailets/pom.xml
tmail-backend/mailets/src/main/java/com/linagora/tmail/mailet/IsALDAPMailingList.java
tmail-backend/mailets/src/main/java/com/linagora/tmail/mailet/LDAPMailingList.java
tmail-backend/mailets/src/test/java/com/linagora/tmail/mailet/IsALDAPMailingListTest.java
tmail-backend/mailets/src/test/java/com/linagora/tmail/mailet/LDAPMailingListTest.java
tmail-backend/mailets/src/test/resources/ldif-files/populate.ldif
tmail-backend/smtp-extensions/pom.xml
tmail-backend/smtp-extensions/src/main/java/com/linagora/tmail/smtp/NaiveTMailWithMailingListsValidRcptHandler.java
tmail-backend/smtp-extensions/src/main/java/com/linagora/tmail/smtp/TMailWithMailingListValidRcptHandler.java
tmail-backend/smtp-extensions/src/test/java/com/linagora/tmail/smtp/NaiveTMailWithMailingListsValidRcptHandlerTest.java
tmail-backend/smtp-extensions/src/test/java/com/linagora/tmail/smtp/TMailWithMailingListValidRcptHandlerTest.java
tmail-backend/smtp-extensions/src/test/resources/ldif-files/populate.ldif

Ldap mailing lists

---

tmail-backend/event-bus-redis/src/main/scala/org/apache/james/events/RedisEventBusClientFactory.scala
tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusTest.java
tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusWithRedisSentinelTest.java

The test suite could encounter lettuce OOM errors after running for a while.

Fix Redis event bus unstable tests

---

docs/modules/ROOT/pages/tmail-backend/smtp-extensions/tmailValidRcptHandler.adoc

resolve https://github.com/linagora/tmail-backend/issues/1149

ISSUE-1149 [Document] TMail validate reception handler

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/PublicAssetSetMethodContract.scala
tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/CassandraPublicAssetRepository.scala
tmail-backend/jmap/extensions-cassandra/src/test/java/com/linagora/tmail/james/jmap/publicAsset/CassandraPublicAssetServiceTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetRepository.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetSetRequest.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetSetService.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/publicAsset/PublicAssetStorage.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/publicAsset/MemoryPublicAssetServiceTest.scala

resolve https://github.com/linagora/tmail-backend/issues/1164

ISSUE-1164 Update the handle message when exceeding public asset quota limit

---

tmail-backend/deployment-tests/common/src/main/java/com/linagora/tmail/deployment/ThirdPartyContainers.java

To match the version on James side.

Upgrades images version for deployment tests

---

tmail-backend/apps/distributed/docker-compose.yml

Update service tmail-backend healthcheck for docker-compose sample file

---

docs/modules/ROOT/pages/tmail-backend/features/ldapMailingLists.adoc
tmail-backend/mailets/src/main/java/com/linagora/tmail/mailet/LDAPMailingList.java
tmail-backend/mailets/src/test/java/com/linagora/tmail/mailet/LDAPMailingListTest.java
tmail-backend/mailets/src/test/resources/ldif-files/populate.ldif

`businessCategory: cn=memberRestrictedList,ou=twakeListType,ou=nomenclature,o=gov,c=mu`
=> businessCategory = memberRestrictedList

ISSUE-1208 Allow use of custom schema for LDAP Mailing lists

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LabelGetMethodContract.scala

resolve https://github.com/linagora/tmail-backend/issues/1241

ISSUE-1241 Fix LabelGetMethodContract test - asserts the vault extension

---

.scalafix.conf

Make it similar to James
https://github.com/apache/james-project/blob/master/.scalafix.conf#L35

Checkstyle - support avoid debug code

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/james/app/DisabledEmailAddressContactSearchEngineModule.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEchoMethodContract.scala
tmail-backend/jmap/extensions-opensearch/src/main/java/com/linagora/tmail/james/jmap/module/OSContactAutoCompleteModule.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContact.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ContactAutocompleteMethod.scala

resolve https://github.com/linagora/tmail-backend/issues/1209

ISSUE-1209 Auto-complete: return minimum characters to autocomplete in the capability object

---

tmail-backend/blob/secondary-blob-store/src/main/java/com/linagora/tmail/blob/secondaryblobstore/SecondaryBlobStoreDAO.java

resolve https://github.com/linagora/tmail-backend/issues/1232

ISSUE-1232 SecondaryBlobStoreDAO should use FileBackedOutputStream to back save()

---

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/WebFingerRoutesContract.scala
tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/JMAPExtensionConfiguration.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventReplyPerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EmailRecoveryActionSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/oidc/WebFingerRoutes.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ticket/TicketManager.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/ticket/TicketManagerTest.scala

resolve https://github.com/linagora/tmail-backend/issues/1240

ISSUE-1240 WebSocket: ability to disable IP check for ticket authentication

---

tmail-backend/apps/postgres/README.md
tmail-backend/apps/postgres/clean_up_data_tmail.sql
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/jmap/extensions-postgres/src/main/scala/com/linagora/tmail/james/jmap/ticket/PostgresTicketStore.scala
tmail-backend/jmap/extensions-postgres/src/test/java/com/linagora/tmail/james/jmap/ticket/PostgresTicketStoreTest.java
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/ticket/TicketStoreContract.scala

resolve https://github.com/linagora/tmail-backend/issues/1239

ISSUE-1239 Implement PostgresTicketStore

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedSearchSnippetGetMethodTest.java

Guice binding for SearchSnippet/get

---

dockerfiles/jenkins-runner/Dockerfile
tmail-backend/apps/distributed/README.md
tmail-backend/apps/memory/README.md

when trying to run demos and run james, i encountered several small issues that needed the fixups i suggest here.

small version updates and fixups

---

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc

Taken over from https://github.com/apache/james-project/pull/2482

[Documentation] Structured logging

---

tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedCleanupIntegrationContract.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedInboxArchivalIntegrationContract.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedJmapUploadCleanRouteIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedProtocolServerIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedRecomputeQuotaTeamMailboxesRouteIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedRspamdFeedMessageRouteIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUserDeletionIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUsernameChangeIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/resources/firebase.properties
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebaseCommonModule.java
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebaseSubscriptionDisconnector.java

resolve https://github.com/linagora/tmail-backend/issues/1334

ISSUE-1334 Disconnection for FCM

---

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/ContactAddedRabbitMqMessage.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/OpenPaasContactsConsumer.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/OpenPaasContactsConsumerTest.java

https://github.com/linagora/tmail-backend/issues/1371#issuecomment-2519149348

[ISSUE-1163] - Update ContactAddedRabbitMqMessage deserializer (ignore fail when unknown properties)

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/contactSupport.adoc
tmail-backend/guice/protocols/jmap/src/test/java/com/linagora/tmail/module/LinagoraTestJMAPServerModule.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraContactSupportCapabilityContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraContactSupportCapabilityTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ContactSupportCapabilitiesModule.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/JMAPExtensionConfiguration.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/JMAPExtensionConfigurationTest.scala

resolve  https://github.com/linagora/tmail-backend/issues/1202

ISSUE-1201 [MU] JMAP extension: contact the support - http link

---

tmail-backend/mailets/src/main/java/com/linagora/tmail/mailet/LDAPMailingList.java
tmail-backend/smtp-extensions/src/main/java/com/linagora/tmail/smtp/TMailWithMailingListValidRcptHandler.java

Deployed with a local JAR on MU

[FIX] Do not apply user filters for mailing lists

---

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/api/OpenPaasRestClient.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/ContactRabbitMqMessage.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/OpenPaasContactsConsumer.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/OpenPaasContactsConsumerTest.java

resolve https://github.com/linagora/tmail-backend/issues/1392

ISSUE-1392 OpenPaasContactsConsumer: Failed to retrieve user mail using OpenPaas id null 

---

docs/modules/ROOT/pages/tmail-backend/configure/openpaas.adoc
docs/modules/ROOT/pages/tmail-backend/configure/standalone-calendar.adoc
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/guice/distributed/src/test/java/com/linagora/tmail/james/app/TestRabbitMQModule.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventReplyWithAMQPWorkflowTest.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/AmqpUri.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/OpenPaasModule.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/configuration/OpenPaasConfiguration.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/OpenPaasContactsConsumer.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/OpenPaasAmqpForwardAttributeIntegrationTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/configuration/OpenPaasConfigurationTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/OpenPaasContactsConsumerTest.java
tmail-backend/tmail-third-party/openpaas/src/test/scala/com/linagora/tmail/api/OpenPaasRestClientTest.java

need https://github.com/apache/james-project/pull/2548
resolve #1370

ISSUE-1370 Quorum queue for OpenPaaS extension

---

tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/SchedulerReconnectionHandlerIntegrationTest.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/ScheduledReconnectionHandler.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/OpenPaasModule.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/OpenPaasContactsConsumer.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/OpenPaasContactsConsumerReconnectionHandler.java

tackling [issue 1359](https://github.com/linagora/tmail-backend/issues/1359)

[ISSUE-1359] reconnection handling for openpaas contact consumer

---

tmail-backend/jmap/extensions/pom.xml
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/AttendanceStatus.java
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/EventAttendanceRepository.java
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/StandaloneEventAttendanceRepository.java
tmail-backend/jmap/extensions/src/test/java/com/linagora/tmail/james/jmap/StandaloneEventAttendanceRepositoryTest.java

Closes https://github.com/linagora/tmail-backend/issues/1326

Introduce StandaloneEventAttendanceRepository

---

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/JCardObject.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/JCardObjectDeserializer.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/OpenPaasContactsConsumer.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/JCardObjectDeserializerTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/JCardObjectTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/OpenPaasContactsConsumerTest.java

TODO debug fail tests in `OpenPaasContactsConsumerTest`.
```java
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a Lambda expression in com.linagora.tmail.contact.OpenPaasContactsConsumerTest [List check first element] 
expected: ContactFields(john@doe.com,John Dont,)
but was: ContactFields(john@doe.com,John,Doe) within 10 seconds.
Expected :ContactFields(john@doe.com,John Dont,)
Actual   :ContactFields(john@doe.com,John,Doe)
```

ISSUE-1382 One vcard should support multiple addresses

---

tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RabbitMQAndRedisEventBus.java
tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/TMailEventDispatcher.java
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/TmailEventSerializer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/TMailDistributedWebSocketTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/pom.xml
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/TmailJmapEventSerializer.scala

following https://github.com/apache/james-project/pull/2567

Rebase Redis event bus

---

tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RedisKeyRegistrationHandler.java

ISSUE-1414 RedisKeyRegistrationHandler: silent error logs upon shutdown

---

tmail-backend/plugins/mail-reporting/src/main/java/com/linagora/tmail/api/MailReportEntry.java
tmail-backend/plugins/mail-reporting/src/main/java/com/linagora/tmail/cassandra/CassandraMailReportGenerator.java
tmail-backend/plugins/mail-reporting/src/main/java/com/linagora/tmail/mailet/MailReportRecorder.java
tmail-backend/plugins/mail-reporting/src/main/java/com/linagora/tmail/route/MailReportsRoute.java
tmail-backend/plugins/mail-reporting/src/test/java/com/linagora/tmail/api/MailReportGeneratorContract.java
tmail-backend/plugins/mail-reporting/src/test/java/com/linagora/tmail/route/TMailReportsIntegrationTest.java

[MU] Add size in the report

---

Jenkinsfile

ref https://github.com/linagora/james-project-private/issues/923

Update Jenkinsfile - agent any

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/guice/distributed/src/test/java/com/linagora/tmail/james/app/TestRabbitMQModule.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventReplyWithAMQPWorkflowTest.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/AmqpUri.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/OpenPaasContactsConsumerModule.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/configuration/OpenPaasConfiguration.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/AmqpUriTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/OpenPaasAmqpForwardAttributeIntegrationTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/configuration/OpenPaasConfigurationTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/OpenPaasContactsConsumerTest.java
tmail-backend/tmail-third-party/openpaas/src/test/scala/com/linagora/tmail/api/OpenPaasRestClientTest.java

[FIX] Inject OpenPaaS module correctly

---

tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/TmailLocalDelivery.scala

placeholder to adapt https://github.com/apache/james-project/pull/2582

Update JAMES sha1

---

tmail-backend/event-bus-redis/pom.xml
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/ContactRabbitMqMessage.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/OpenPaasContactsConsumerTest.java

ISSUE-1441 ContactRabbitMqMessage: add fallback parsing userId using `$.user._id`

---

tmail-backend/integration-tests/imap/memory-imap-integration-tests/src/test/java/com/linagora/tmail/imap/IMAPTeamMailboxIntegrationTest.java

ref https://github.com/linagora/tmail-backend/issues/1415#issuecomment-2576614001

ISSUE-1272 - IMAP LIST - add more test for #TeamMailbox when SUBSCRIBED in request option

---

tmail-backend/blob/secondary-blob-store/src/main/java/com/linagora/tmail/blob/secondaryblobstore/FailedBlobOperationListener.java
tmail-backend/blob/secondary-blob-store/src/main/java/com/linagora/tmail/blob/secondaryblobstore/SecondaryBlobStoreDAO.java

- Always include blobId
- INFO log upon resync

[FIX] Improve logging for SecondaryBlobStoreDAO

---

tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RedisKeyRegistrationHandler.java

resolve https://github.com/linagora/james-project/issues/5381

WIP - ISSUE-5381 Fix RedisKeyRegistrationHandler could not deserialize list event

---

tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RedisKeyRegistrationBinder.java
tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RedisKeyRegistrationHandler.java

Should not be needed anymore as the Redis event bus is more or less stable now.

[IMPROVEMENT] Remove some Redis event bus debug logs

---

tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/TMailEventDispatcher.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/WebFingerRoutesContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EncryptedAttachmentBlobResolver.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/oidc/WebFingerRoutes.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ticket/TicketRoutes.scala

fix https://github.com/linagora/tmail-backend/pull/1479

Update James SHA-1 (manually)

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/DownloadAllContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/routes/DownloadAllRoutes.scala

resolve https://github.com/linagora/tmail-backend/issues/1495

ISSEU-1495 Implement Download all capability

---

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc
docs/modules/ROOT/pages/tmail-backend/configure/jvm.adoc
tmail-backend/apps/memory/src/main/conf/jvm.properties
tmail-backend/guice/blob-guice/src/main/java/com/linagora/tmail/blob/guice/BlobStoreConfiguration.java
tmail-backend/imap-extensions/src/main/java/com/linagora/tmail/imap/TMailFullDomainPathConverter.java
tmail-backend/imap-extensions/src/main/java/com/linagora/tmail/imap/TMailPathConverter.java
tmail-backend/imap-extensions/src/main/java/com/linagora/tmail/imap/TMailPathConverterFactory.java
tmail-backend/imap-extensions/src/test/java/com/linagora/tmail/imap/TMailPathConverterFactoryTest.java
tmail-backend/imap-extensions/src/test/java/org/apache/james/imap/main/TMailFullDomainPathConverterTest.java
tmail-backend/imap-extensions/src/test/java/org/apache/james/imap/main/TeamMailboxFullDomainPathConverterContract.java

Allow showing full mail address of team mailboxes in mail client. This can be toggled via configuration - the default will be to still use the current version of the `TMailPathConverter` (domain part omitted).
@chibenwa This *almost* resolves what we had in mind with #1405, it is just the integration with the not-yet-merged postgres branch that is missing.
The change did get slightly larger than anticipated, but that is mainly due to the tests and a couple of licence headers :wink:

ISSUE-1405: Teammailbox fulldomain

---

tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TMailCanSendFrom.scala

Fix the forgot update related code when change type of method 
teamMailboxRepository.listMembers from `Username` -> `TeamMailboxMember`

ISSUE-1087 Add member role to TeamMailboxRepository - fixup

---

tmail-backend/integration-tests/imap/memory-imap-integration-tests/src/test/java/com/linagora/tmail/imap/IMAPTeamMailboxIntegrationTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailCanSendFromTest.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailQuotaRootResolverTest.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TeamMailboxRepositoryContract.scala
tmail-backend/mailets/src/test/java/com/linagora/tmail/mailet/LinagoraMailetContextTest.java
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/IsTeamMailboxTest.scala
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/TMailMailboxAppenderTest.scala
tmail-backend/smtp-extensions/src/test/java/com/linagora/tmail/smtp/NaiveTMailWithMailingListsValidRcptHandlerTest.java
tmail-backend/smtp-extensions/src/test/java/com/linagora/tmail/smtp/TMailValidRcptHandlerTest.java
tmail-backend/smtp-extensions/src/test/java/com/linagora/tmail/smtp/TMailWithMailingListValidRcptHandlerTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/RecomputeQuotaTeamMailboxesRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/TeamMailboxQuotaRoutesTest.java
tmail-backend/webadmin/webadmin-team-mailboxes/src/test/java/com/linagora/tmail/webadmin/UserTeamMailboxRoutesTest.java

resolve https://github.com/linagora/tmail-backend/issues/1505

ISSUE-1505 Team mailbox: ability to create folders

---

tmail-backend/tmail-third-party/openpaas/pom.xml

This was pulling testing dependencies into production

Add missing test scope

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/oidc/WebFingerRoutes.scala

This helps other mail clients like Parula or mailTemi to discover OpenID connect server location
(they do not implement OpenID dynamic discovery spec)

[ENHANCEMENT] Redirect to OpenID session

---

tmail-backend/guice/team-mailboxes/src/main/java/com/linagora/tmail/team/TeamMailboxModule.java
tmail-backend/integration-tests/imap/memory-imap-integration-tests/src/test/java/com/linagora/tmail/imap/IMAPTeamMailboxIntegrationTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/PropagateDeleteRightTeamMailboxListener.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxProbe.scala
tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala
tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/PropagateDeleteRightTeamMailboxListenerTest.scala

resolve https://github.com/linagora/tmail-backend/issues/1530

ISSUE-1530 Team mailbox: ability to remove custom folders

---

tmail-backend/integration-tests/imap/memory-imap-integration-tests/src/test/java/com/linagora/tmail/imap/IMAPTeamMailboxIntegrationTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala

resolve https://github.com/linagora/tmail-backend/issues/1552

ISSUE-1552 Team mailboxes: ability to rename custom folders

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala

Need time for distributed indexing 
-> using `Awaitility`

ISSUE-261 JMAP for TeamMailboxes: Thread/get - fix unstable distributed test `threadGetShouldHandleTeamMailboxEmail`

---

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/OpenPaasModule.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/DockerOpenPaasExtension.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/DockerOpenPaasExtensionTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/DockerOpenPaasSetup.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/OpenPaaSProvisioningService.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/OpenPaasSetupTestModule.java

Setup some OpenPaas/CalDAV guice bindings

---

tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests/src/test/java/com/linagora/tmail/james/PostgresEmailGetMethodTest.java

backport https://github.com/linagora/tmail-backend/pull/1508 for postgres
resolve #1532

ISSUE-1532 [Postgresql] Backport bundle compute JMAP preview into OpenSearch indexing

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventAttendanceGetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/CalendarEventAttendanceSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventAttendanceGetMethod.scala

resolve https://github.com/linagora/tmail-backend/issues/1594

ISSUE-1594 JMAP - CalendarEventAttendance/get - refactor response body

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/CalendarEventSupportCapabilityContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventParseMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/pom.xml
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventSupportCapabilityTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventParseMethod.scala
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/OpenPaasModule.java

ref https://github.com/linagora/tmail-backend/issues/1567

ISSUE-1567 Calendar - free-busy extension - session capability

---

tmail-backend/mailbox/listeners/src/main/java/com/linagora/tmail/event/ComputePreviewMessageIndexer.java

need https://github.com/apache/james-project/pull/2678

[FIX] ComputePreviewMessageIndexer: fix NPE when Expunged event

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/openpaas/DistributedOpenPaaSCalendarEventMaybeMethodTest.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/openpaas/DistributedOpenPaaSCalendarEventRejectMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventMaybeMethodContract.scala
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventRejectMethodContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraCalendarEventMaybeMethodTest.java
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraCalendarEventRejectMethodTest.java
tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests/src/test/java/com/linagora/tmail/james/PostgresLinagoraCalendarEventMaybeMethodTest.java
tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests/src/test/java/com/linagora/tmail/james/PostgresLinagoraCalendarEventRejectMethodTest.java

Propagate calendar event accept method integration test changes to other methods

---

tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/DistributedServerWithRedisEventBusKeysTest.java
tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/RabbitMQAndRedisEventBusProbe.java
tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RabbitMQAndRedisEventBus.java
tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/RedisKeyRegistrationHandler.java

#1615 should have been fixed by https://github.com/linagora/tmail-backend/pull/1457

ISSUE-1615 Redis event bus: add a test for multiple events deserialization

---

twake-calendar-side-service/app/src/main/conf/configuration.properties
twake-calendar-side-service/app/src/test/java/com/linagora/calendar/app/TwakeCalendarGuiceServerTest.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/FallbackProxy.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/RestApiConfiguration.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/RestApiModule.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/auth/OidcAuthenticationStrategy.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/routes/JwtSigner.java

Real deployment

---

twake-calendar-side-service/app/src/test/java/com/linagora/calendar/app/TwakeCalendarGuiceServerTest.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/RestApiModule.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/routes/configuration/AllowDomainAdminToManageUserEmailsConfigurationEntryResolver.java

Needed to have the account page working...

Implement AllowDomainAdminToManageUserEmailsConfigurationEntryResolver

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraContactAutoCompleteMethodTest.java
tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests/src/test/java/com/linagora/tmail/james/PostgresLinagoraContactAutoCompleteMethodTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUserDeletionIntegrationTest.java
tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedUsernameChangeIntegrationTest.java
tmail-backend/integration-tests/webadmin/postgres-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/postgres/PostgresUserDeletionIntegrationTest.java
tmail-backend/integration-tests/webadmin/postgres-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/postgres/PostgresUsernameChangeIntegrationTest.java
tmail-backend/jmap/extensions-opensearch/src/main/java/com/linagora/tmail/james/jmap/OSEmailAddressContactSearchEngine.java
tmail-backend/jmap/extensions-opensearch/src/test/java/com/linagora.tmail.james.jmap.model/OSEmailAddressContactSearchTest.java

OSEmailAddressContactSearchEngine - update deprecated method of opensearch java library

---

twake-calendar-side-service/app/pom.xml
twake-calendar-side-service/app/src/main/java/com/linagora/calendar/app/TwakeCalendarConfiguration.java
twake-calendar-side-service/app/src/main/java/com/linagora/calendar/app/TwakeCalendarMain.java
twake-calendar-side-service/app/src/main/java/com/linagora/calendar/app/modules/MemoryAutoCompleteModule.java
twake-calendar-side-service/app/src/main/java/com/linagora/calendar/app/modules/OpenSearchClientModule.java
twake-calendar-side-service/app/src/test/java/com/linagora/calendar/app/TwakeCalendarGuiceServerTest.java
twake-calendar-side-service/calendar-rest-api/pom.xml
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/RestApiConfiguration.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/RestApiModule.java
twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/routes/PeopleSearchRoute.java

Bootstraps people API on top of opensearch

Twake Calendar Side Service: People search

---

tmail-backend/jmap/extensions-api/src/main/java/com/linagora/tmail/james/jmap/EventAttendanceRepository.java
tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventModifier.scala
tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/calendar/CalendarResolver.scala
tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventParse.scala
tmail-backend/jmap/extensions-api/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventModifierTest.scala
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/StandaloneEventRepository.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/TMailJMAPModule.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventAcceptMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventAttendanceStatusPerformer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventMaybeMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventParseMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventRejectMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventReplyMailProcessor.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventReplyPerformer.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/StandaloneEventRepositoryTest.scala
tmail-backend/tmail-third-party/openpaas/pom.xml
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/OpenPaasModule.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/dav/CalDavEventRepository.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/dav/DavCalendarObject.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/CalDavEventRepositoryTest.java

resolve https://github.com/linagora/tmail-backend/issues/1652

ISSUE-1652 Fix bug CalendarEvent/accept, reject, maybe when recurrence event

---

pom.xml

Could not manage to get something conclusive. 
Stable at mean time 320 ms.

[ENHANCEMENT] Adopt JRE 24

---

tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RedisEventBusServiceTest.java
tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RedisPlaygroundTest.java

cf https://github.com/linagora/james-project-private/issues/1052
**TL;DR:** Basically, Redis event bus continues to function well after a Redis standalone restart.
- The **Lettuce driver** [handles reconnection automatically](https://javadoc.io/static/io.lettuce/lettuce-core/6.5.5.RELEASE/io/lettuce/core/protocol/ConnectionWatchdog.html) when Redis becomes available again after a restart, so there is **no need to restart TMail**.
Overall, the impact is minimal:
- No issues.
- They can subscribe to notifications normally after the restart, and receive notifications well.
- Subscriptions are lost after the Redis restart.
- Users will need to **re-subscribe**, either via **IMAP SELECT** or refreshing the **WebSocket push** connection for example.
- The previous registrations are …

Tests for Redis event bus when Redis standalone restart

---

docs/modules/ROOT/pages/tmail-backend/configure/openpaas.adoc
tmail-backend/tmail-third-party/openpaas/sample_conf/openpaas.properties
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/api/OpenPaasRestClient.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/configuration/DavConfiguration.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/configuration/OpenPaasConfiguration.java
tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/dav/DavClient.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/DockerOpenPaasSetup.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/OpenPaasTestModule.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/configuration/DavConfigurationTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/configuration/OpenPaasConfigurationTest.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/dav/DavServerExtension.java

ISSUE-1714 OpenPaaS extension: make REST API timeout configurable

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/mailboxClear.adoc
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedMailboxClearMethodTest.java
tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/MailboxClearContract.scala
tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryMailboxClearMethodTest.java
tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests/src/test/java/com/linagora/tmail/james/PostgresMailboxClearMethodTest.java
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/MailboxClearSerializer.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/MailboxClearMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/MailboxClear.scala
tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/MailboxClearSerializerTest.scala

ISSUE-1722 Implement Mailbox/clear extension

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/MailboxClearMethod.scala

20k mails, before: 15 seconds
20k mails, after: 10 seconds

ISSUE-1732 Increase Mailbox/clear deletion batch

---

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedJamesConfiguration.java
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailConfiguration.java
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java
tmail-backend/guice/distributed/pom.xml
tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/james/jmap/oidc/OidcTokenCacheModuleChooser.java
tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedOidcAuthenticationTest.java
tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests/pom.xml
tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests/src/test/java/com/linagora/tmail/james/PostgresOidcAuthenticationTest.java
tmail-backend/jmap/extensions-redis/pom.xml
tmail-backend/jmap/extensions-redis/src/main/java/com/linagora/tmail/james/jmap/oidc/RedisOidcTokenCache.java
tmail-backend/jmap/extensions-redis/src/main/java/com/linagora/tmail/james/jmap/oidc/RedisOidcTokenCacheModule.java
tmail-backend/jmap/extensions-redis/src/main/java/com/linagora/tmail/james/jmap/oidc/RedisTokenCacheCommands.java
tmail-backend/jmap/extensions-redis/src/main/scala/com/linagora/tmail/james/jmap/oidc/RedisConfigurationUtils.scala
tmail-backend/jmap/extensions-redis/src/test/java/com/linagora/tmail/james/jmap/oidc/RedisClusterOidcTokenCacheTest.java
tmail-backend/jmap/extensions-redis/src/test/java/com/linagora/tmail/james/jmap/oidc/RedisOidcTokenCacheContract.java
tmail-backend/jmap/extensions-redis/src/test/java/com/linagora/tmail/james/jmap/oidc/RedisSentinelOidcTokenCacheTest.java
tmail-backend/jmap/extensions-redis/src/test/java/com/linagora/tmail/james/jmap/oidc/RedisStandaloneOidcTokenCacheTest.java
tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/oidc/CaffeineOidcTokenCacheModule.java
tmail-backend/pom.xml

ISSUE-1718 [OIDC] Redis cache implementation

---

docs/modules/ROOT/pages/tmail-backend/configure/opensearch.adoc
tmail-backend/apps/distributed/src/main/conf/opensearch.properties
tmail-backend/apps/postgres/sample-configuration/distributed/opensearch.properties
tmail-backend/mailbox/listeners/src/test/java/com/linagora/tmail/event/TMailComputeMessageFastViewProjectionListenerTest.java
tmail-backend/mailbox/opensearch/src/main/java/com/linagora/tmail/mailbox/opensearch/TmailCriterionConverter.java
tmail-backend/mailbox/opensearch/src/main/java/com/linagora/tmail/mailbox/opensearch/TmailMailboxMappingFactory.java
tmail-backend/mailbox/opensearch/src/main/java/com/linagora/tmail/mailbox/opensearch/TmailOpenSearchMailboxConfiguration.java
tmail-backend/mailbox/opensearch/src/main/java/com/linagora/tmail/mailbox/opensearch/TmailOpenSearchMailboxMappingModule.java
tmail-backend/mailbox/opensearch/src/test/java/com/linagora/tmail/mailbox/opensearch/TmailOpenSearchIntegrationTest.java

relying on https://github.com/linagora/tmail-backend/pull/1781

Subject ngrams

---

docs/modules/ROOT/pages/tmail-backend/configure/opensearch.adoc
tmail-backend/apps/distributed/src/main/conf/opensearch.properties
tmail-backend/apps/postgres/sample-configuration/distributed/opensearch.properties
tmail-backend/mailbox/opensearch/pom.xml
tmail-backend/mailbox/opensearch/src/main/java/com/linagora/tmail/mailbox/opensearch/TmailCriterionConverter.java
tmail-backend/mailbox/opensearch/src/main/java/com/linagora/tmail/mailbox/opensearch/TmailMailboxMappingFactory.java
tmail-backend/mailbox/opensearch/src/main/java/com/linagora/tmail/mailbox/opensearch/TmailOpenSearchMailboxConfiguration.java
tmail-backend/mailbox/opensearch/src/test/java/com/linagora/tmail/mailbox/opensearch/TmailOpenSearchIntegrationTest.java
tmail-backend/mailbox/opensearch/src/test/resources/eml/template/attachment-filename.eml.mustache

ISSUE-1776 Attachment filename ngram search

---

demo/docker-compose.yml
demo/tmail/ai.properties
demo/tmail/extensions.properties
demo/tmail/mailetcontainer.xml

closes #1789 
adding aibot config to ai.properties and removing it from mailetContainer.xml, adding extension modules for aiBot
updating the jar with the new aibot with dependencies

Updating demo to use the new extensionMecanism

---

pom.xml

Based on https://github.com/linagora/tmail-backend/pull/1811

Update James-sha1 with plugins

---

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/mailet/CardDavCollectedContact.java
tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/CardDavCollectedContactIntegrationTest.java

ISSUE-1816 Users should have contacts indexed when using alias address to send mail

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TWPSettingsContract.scala
tmail-backend/jmap/extensions-rabbitmq/src/main/java/com/linagora/tmail/james/jmap/settings/TWPSettingsConsumer.java

resolve #1824
To avoid potential race condition when concurrent TWP settings updates. Given that the TWP settings update should not be a frequent action, and updating the settings on the TMail side should be fast, consuming TWP settings updates serially should be acceptable.

ISSUE-1824 TWP settings queue should be single active consumer bound

---

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ContactSupportCapabilitiesModule.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventParseMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ContactAutocompleteMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FilterGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ForwardGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/JmapSettingsGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/KeystoreSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/MailboxClearMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/MessageVaultCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/PublicAssetsCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/routes/DownloadAllRoutes.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxesCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ticket/TicketRoutes.scala
tmail-backend/tmail-third-party/ai-bot/src/main/scala/com/linagora/tmail/jmap/aibot/AiBotCapability.scala

Update James SHA1 and adapt https://github.com/apache/james-project/pull/2781 change.

[TMail] CapabilityFactory should take Username into account

---

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraForwardSetMethodContract.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ContactSupportCapabilitiesModule.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventParseMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ContactAutocompleteMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CustomMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FilterGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/FirebaseCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ForwardGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ForwardSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/JmapSettingsGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/KeystoreSetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/LabelGetMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/MailboxClearMethod.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/MessageVaultCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/PublicAssetsCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/ForwardSet.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/routes/DownloadAllRoutes.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxesCapability.scala
tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/ticket/TicketRoutes.scala
tmail-backend/tmail-third-party/ai-bot/src/main/scala/com/linagora/tmail/jmap/aibot/AiBotCapability.scala

resolve https://github.com/linagora/tmail-flutter/issues/3922

[FIX] Forward/set should return failure response when users configure a forward loop

---

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/index.adoc
docs/modules/ROOT/pages/tmail-backend/jmap-extensions/saas.adoc

Resolve docs need for https://github.com/linagora/tmail-backend/issues/1840#issuecomment-3218640969

ISSUE-1840 Add JMAP SaaS capability documentation

---

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedEmailSubmissionSetMethodTest.java
tmail-backend/jmap/extensions/src/test/java/com/linagora/tmail/james/jmap/perfs/TMailCleverMessageParserTest.java

the sha-1 update for having this test here: https://github.com/apache/james-project/pull/2787
(yes didn't feel like rewritting a scala test in java^^)

Fix jmap emailsubmission/set attachment

---

tmail-backend/tmail-third-party/ai-bot/src/test/java/com/linagora/tmail/mailet/rag/RagListenerTest.java

ISSUE-1880 [BUILD] RagListenerTest: wire mock server should use dynamic port

---

tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/pom.xml

CF https://github.com/linagora/tmail-backend/pull/1886
Opened another PR becase the bot force pushed me.

Upgrade sha1

---

tmail-backend/data/data-cassandra/src/main/java/com/linagora/tmail/user/cassandra/TMailCassandraUsersRepositoryDataDefinition.java
tmail-backend/data/data-postgres/src/main/java/com/linagora/tmail/user/postgres/TMailPostgresUserDataDefinition.java
tmail-backend/rate-limiter/rate-limiter-api/src/main/java/com/linagora/tmail/rate/limiter/api/RateLimitingRepository.java
tmail-backend/rate-limiter/rate-limiter-api/src/main/java/com/linagora/tmail/rate/limiter/api/memory/MemoryRateLimitingRepository.java
tmail-backend/rate-limiter/rate-limiter-api/src/main/java/com/linagora/tmail/rate/limiter/api/model/RateLimitingDefinition.java
tmail-backend/rate-limiter/rate-limiter-api/src/main/scala/com/linagora/tmail/rate/limiter/api/memory/MemoryRateLimitingModule.scala
tmail-backend/rate-limiter/rate-limiter-api/src/test/java/com/linagora/tmail/rate/limiter/api/RateLimitingRepositoryContract.java
tmail-backend/rate-limiter/rate-limiter-api/src/test/java/com/linagora/tmail/rate/limiter/api/memory/MemoryRateLimitingRepositoryTest.java
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/java/com/linagora/tmail/rate/limiter/api/cassandra/CassandraRateLimitingRepository.java
tmail-backend/rate-limiter/rate-limiter-cassandra/src/main/scala/com/linagora/tmail/rate/limiter/api/cassandra/module/CassandraRateLimitingModule.scala
tmail-backend/rate-limiter/rate-limiter-cassandra/src/test/java/com/linagora/tmail/rate/limiter/api/cassandra/CassandraRateLimitingRepositoryTest.java
tmail-backend/rate-limiter/rate-limiter-postgres/src/main/java/com/linagora/tmail/rate/limiter/api/postgres/PostgresRateLimitingRepository.java
tmail-backend/rate-limiter/rate-limiter-postgres/src/main/scala/com/linagora/tmail/rate/limiter/api/postgres/module/PostgresRateLimitingModule.scala
tmail-backend/rate-limiter/rate-limiter-postgres/src/test/java/com/linagora/tmail/rate/limiter/api/postgres/PostgresRateLimitingRepositoryTest.java
upgrade-instructions.md

rework of https://github.com/linagora/tmail-backend/pull/1895
resolve #1888

ISSUE-1888 Implement RateLimitingRepository

---

docs/modules/ROOT/pages/tmail-backend/features/tmailRateLimiting.adoc
tmail-backend/mailets/pom.xml
tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/ReceivedRateLimiting.scala
tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/SentRateLimiting.scala
tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/TmailMailRateLimiter.scala
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/ReceivedRateLimitingTest.scala
tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/SentRateLimitingTest.scala

ISSUE-1889 Implement enforce rate limiting mailet(s)

---

docs/modules/ROOT/pages/tmail-backend/webadmin.adoc
tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedSaaSModule.java
tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemorySaaSModule.java
tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresSaaSModule.java
tmail-backend/saas/saas-api/src/main/java/com/linagora/tmail/saas/api/SaaSAccountRepository.java
tmail-backend/saas/saas-api/src/main/java/com/linagora/tmail/saas/api/SaaSAccountUsernameChangeTaskStep.java
tmail-backend/saas/saas-api/src/main/java/com/linagora/tmail/saas/api/memory/MemorySaaSAccountRepository.java
tmail-backend/saas/saas-api/src/test/java/com/linagora/tmail/saas/api/SaaSAccountRepositoryContract.java
tmail-backend/saas/saas-api/src/test/java/com/linagora/tmail/saas/api/SaaSAccountUsernameChangeTaskStepTest.java
tmail-backend/saas/saas-cassandra/src/main/java/com/linagora/tmail/saas/api/cassandra/CassandraSaaSAccountRepository.java
tmail-backend/saas/saas-cassandra/src/test/java/com/linagora/tmail/saas/api/cassandra/CassandraSaaSAccountRepositoryTest.java
tmail-backend/saas/saas-postgres/src/main/java/com/linagora/tmail/saas/api/postgres/PostgresSaaSAccountRepository.java
tmail-backend/saas/saas-postgres/src/test/java/com/linagora/tmail/saas/api/postgres/PostgresSaaSAccountRepositoryTest.java

ISSUE-1887 Implement username change step for SaaS account
