linagora/tmail-backend

Jenkinsfile
The problem of not having builds for PRs yet... (and the fact I didn't test my Jenkinsfile locally either... yes throw me stones)
Well without the steps section, the all pipeline is broken and the build does not start on the CI
=> Add missing steps section in Compile stage

openpaas-james/apps/distributed/pom.xml, openpaas-james/apps/memory/pom.xml, openpaas-james/pom.xml
We need it to generate logs in json for fluentbit to be able to scrap them
=> Add missing logback json dependency in distributed version

openpaas-james/apps/distributed-es6-backport/pom.xml
Yeah well... Same issue as last time, which makes crash the new release on preprod, that got missed on es6-backport as the work was in the same time and not finalized yet. Please help review and merge ASAP thanks :)
=> Add missing logback json dependency in distributed-es6-backport version

openpaas-james/mailbox/encrypted/pgp-utils/src/main/java/com/linagora/openpaas/pgp/Encrypter.java
This prevents frequent disk flushes harming performance.
Needs to be backed by performance tests before being adopted...
=> ISSUE-99 Buffer encrypted stream before writing it on the file system

tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/BlobIdList.scala, tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/SingleSaveBlobStoreDAO.java, tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/cassandra/CassandraBlobIdList.scala, tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/cassandra/CassandraBlobIdListDAO.scala
Scala booleans are not equal to Java ones.
This prevented from benefiting from the change set
Especially we divided by 2 the percentiles of "send message"
=> ISSUE-124 Fix SingleSaveBlobStoreDAO

tmail-backend/mailetcontainer-impl/src/main/java/org/apache/james/mailetcontainer/impl/MatcherSplitter.java
Running CustomMailetProcessing fix inside James memory server
against the mailet integration test suite I realise the fix was
actually missing.
=> JAMES-3589 Apply state preservation fix

tmail-backend/apps/distributed-es6-backport/pom.xml, tmail-backend/apps/distributed/pom.xml, tmail-backend/apps/memory/pom.xml, tmail-backend/pom.xml
The newest commits shipped on MIME4J ships some nice-to-have performance improvments we might want to benefit from 
prior a mime4J release that anyway takes time.
In the meantime, TMAIL, not subject to the release pluging not accepting `-SNAPSHOT` (a bocker for `apache/james-project`) can start using the fully compatible version of MIME4J.
=> [PERFORMANCE] Rely on MIME4J 0.8.5-SNAPSHOT for TMail

tmail-backend/mailbox/encrypted/api/src/main/scala/com/linagora/tmail/encrypted/EncryptedMailboxManager.scala
Ref: https://github.com/linagora/tmail-backend/issues/95
When I use JMAP to set email. The expected is encrypted message, I realized that `EncryptedMailboxManager#getMailboxReactive` does not return `EncryptedMessageManager`. (Don't similar as `getMailbox` method)
=> ISSUE-95 Update getMailBoxReactive method

tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/CombinedIdentityJamesServerTest.java, tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/CombinedUsersRepositoryModule.java
- Explicitly add an initialisation operation to do this
- Add a test ensuring we can sync the users
- Also fix a typo carried over from the LDAP typo
=> ISSUE-157 Configure CombinedUsersRepository

tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/SingleSaveBlobStoreDAO.java, tmail-backend/blob/blobid-list/src/test/java/com/linagora/tmail/blob/blobid/list/SingleSaveBlobStoreContract.scala, tmail-backend/blob/blobid-list/src/test/java/com/linagora/tmail/blob/blobid/list/SingleSaveBlobStoreTest.java
A SingleSaveBlobStore is supposed to only write on the default bucket, and it should not be allowed to delete the default bucket either.
Added some tests to check added above behaviors and also fixed and refactor the contract as things were not making sense with those rules.
=> Fix SingleSaveBlobStoreDAO save blob and deleteBucket methods

tmail-backend/apps/distributed-es6-backport/pom.xml, tmail-backend/apps/distributed/pom.xml, tmail-backend/apps/memory/pom.xml
DEPRECATION NOTICE of adoptopenjdk:
This image is officially deprecated in favor of the eclipse-temurin image,
and will receive no further updates after 2021-08-01 (Aug 01, 2021). Please
adjust your usage accordingly.
https://hub.docker.com/_/adoptopenjdk?tab=tags&page=1&ordering=last_updated&name=11
=> JAMES-3647 Adopt eclipse-temurin:11-jre-focal docker image

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraEmailSendMethodContract.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EmailSendMethod.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/EmailSend.scala
Relate https://github.com/linagora/james-project/issues/4492
=> JMAP Email/send create should use tooLarge when attempt to create an oversize mail

tmail-backend/apps/distributed-es6-backport/pom.xml, tmail-backend/apps/distributed/pom.xml, tmail-backend/apps/memory/pom.xml
- Allows using perf_event inside container, which includes system calls in the stacktrace
- Include line numbers in the flame graph
- Better container support
=> [UPGRADE] async-profiler 2.0 -> 2.7

tmail-backend/apps/distributed-es6-backport/pom.xml, tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/backend-commons/elasticsearch-v6/src/main/java/org/apache/james/backends/es/IndexCreationFactory.java, tmail-backend/backend-commons/elasticsearch-v6/src/test/java/org/apache/james/backends/es/IndexCreationFactoryTest.java, tmail-backend/jmap/extensions-es-v6/pom.xml, tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/ContactMappingFactory.java, tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/ES6EmailAddressContactSearchEngine.java, tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/ElasticSearchContactConfiguration.java, tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/dto/DomainContactDocument.java, tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/dto/UserContactDocument.java, tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/module/ContactIndexCreationUtil.java, tmail-backend/jmap/extensions-es-v6/src/main/java/com/linagora/tmail/james/jmap/module/ES6ContactAutoCompleteModule.java, tmail-backend/jmap/extensions-es-v6/src/test/java/com/linagora/tmail/james/jmap/model/ES6EmailAddressContactAutoCompleteTest.java, tmail-backend/pom.xml
With ES6, we don't have to specify `max.diff.ngram` anymore.
=> ISSUE-328: ES 6 implementation of EmailAddress Search engine

tmail-backend/webadmin/webadmin-email-address-contact/src/main/java/com/linagora/tmail/webadmin/EmailAddressContactRoutes.java, tmail-backend/webadmin/webadmin-email-address-contact/src/test/java/com/linagora/tmail/webadmin/EmailAddressContactRoutesTest.java
GET ALL contact route's path is duplicated with a James domain route's path.
GET https://james-admin.upn.integration-open-paas.org/domains/contacts
```json
{
"statusCode": 404,
"type": "InvalidArgument",
"message": "The domain list does not contain: contacts",
"details": null
}
```
Test if a domain exists route's path: GET http://ip:port/domains/{domainName}
=> ISSUE-367: Avoid duplicated Test if a domain exists route's path

Jenkinsfile, tmail-backend/apps/distributed-es6-backport/pom.xml, tmail-backend/apps/distributed/pom.xml, tmail-backend/apps/memory/pom.xml, tmail-backend/deployment-tests/distributed-es6-backport/src/test/java/com/linagora/tmail/deployment/TmailDistributedEs6Extension.java, tmail-backend/deployment-tests/distributed-ldap/src/test/java/com/linagora/tmail/deployment/TmailDistributedLdapExtension.java, tmail-backend/deployment-tests/distributed/src/test/java/com/linagora/tmail/deployment/TmailDistributedExtension.java, tmail-backend/deployment-tests/memory/src/test/java/com/linagora/tmail/deployment/TmailMemoryExtension.java
When JIB dockerBuild, it created two images: one in it is a draft, and never be removed. (`none` image, no any tag)
By buildTar mode, the image will be saved as a tar file, then we can lazy load it.
Draft images example:
=> Avoid Google jib create draft images

tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/rspamd/RspamdModule.java, tmail-backend/integration-tests/rspamd/distributed-rspamd-integration-tests/src/test/resources/listeners.xml, tmail-backend/integration-tests/rspamd/distributed-rspamd-integration-tests/src/test/resources/mailetcontainer.xml
In case we are deploying TMail without rspamd, the listener will keep trying to connect to Rspamd for any mail activity which results in a lot of errors messages in logs.
It's still possible to add the listener via listeners.xml file
=> [REFACTORING] Remove the binding on the Rspamd listener

tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebasePushClient.java
Data messages (not notifications) for iOS are only accepted with normal priority, and `content-available: true` header to work.
Solved https://github.com/linagora/tmail-flutter/issues/1248#issuecomment-1342164937
=> [FIX] Fix FCM push options for Apple Push Notification Service

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/oidc/WebFingerRoutes.scala
Failure to do so breaks OIDC login in Safari
Cf https://github.com/linagora/tmail-flutter/issues/1297
=> ISSUE-536 Enable CORS for WebFinger

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/CombinedUsersRepositoryModule.java, tmail-backend/combined-identity/src/main/java/com/linagora/tmail/combined/identity/UsersRepositoryModuleChooser.java, tmail-backend/deployment-tests/common/src/main/java/com/linagora/tmail/deployment/JmapContract.java, tmail-backend/deployment-tests/distributed-es6-backport/src/test/java/com/linagora/tmail/deployment/TmailDistributedEs6Extension.java, tmail-backend/deployment-tests/distributed-ldap/src/test/java/com/linagora/tmail/deployment/TmailDistributedLdapExtension.java, tmail-backend/deployment-tests/distributed-ldap/src/test/resources/prepopulated-ldap/populate.ldif, tmail-backend/deployment-tests/distributed/src/test/java/com/linagora/tmail/deployment/TmailDistributedExtension.java, tmail-backend/deployment-tests/memory/src/test/java/com/linagora/tmail/deployment/TmailMemoryExtension.java
So distributed-es6 is ok now, but not ok especially for LDAP user repository mode which requires a fix on James side: https://github.com/apache/james-project/pull/1473
I expect `DistributedLdapJmapTest.sessionRouteShouldReturnDelegatedAccounts` to fail for now.
=> ISSUE-579 Deployment issue with distributed-esv6 version

tmail-backend/mailets/src/main/scala/com/linagora/tmail/mailets/TMailMailboxAppender.scala, tmail-backend/mailets/src/test/scala/com/linagora/tmail/mailets/TMailMailboxAppenderTest.scala
- Cassandra's event loop was blocked 
```json
{"timestamp":"2023-03-14T08:18:02.828Z","level":"ERROR","thread":"s1-io-4","logger":"org.apache.james.transport.mailets.delivery.MailDispatcher","message":"Error while storing mail. This is a final exception.","context":"default","exception":"com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT5S..."}
```
- Furthermore, MailDispatcher retries (if needed) delivering mail on Parallel scheduler, which would throw right away .block in the pipeline.
=> [FIX] Avoid blocking call by TMailLocalDelivery on Cassandra event loop thread

demo/apisix/conf/apisix.yaml, demo/apisix/conf/config.yaml, demo/apisix/test.sh, demo/docker-compose.yml
resolve https://github.com/linagora/tmail-backend/issues/638
Ref: 
- How to configure run with standalone mode: https://github.com/apache/apisix-docker/blob/821b4744a003cdff5eff75c2a1896ec0eaa1089a/debian/docker-entrypoint.sh#L24
=> ISSUE-638 Add APISIX in the demo OIDC docker compose on TMail

demo/apisix/conf/apisix.yaml, demo/tmail/.env, demo/tmail/jmap.properties
Outside of the CORS setup scope, but I am trying to set up a smooth SSO flow for TMail FE + APISIX.
Currently, I can log in to TMail, however, can not do anything more with it because the wrong endpoint was called by TMail FE
TODO: check configuration regarding oidc endpoint, jmap prefix..
=> CORS for APISIX

demo/apisix/conf/apisix.yaml
[demo fix avoid token revoked when OPTIONS request.webm](https://github.com/linagora/tmail-backend/assets/55171818/7d345397-a8af-48e8-a46b-41220373493d)
=> [APISIX] Avoid call TokenRevokedFilter plugin upon OPTIONS request

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/contact/ContactUserDeletionTaskStep.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/ContactUserDeletionTaskStepTest.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/ContactUsernameChangeTaskStepTest.scala
IMO there should be no reason that other users still be suggested a deleted user contact. Some deployments may not depend on LSC/LDAP to sync the deletion for domain contact.
=> ISSUE-666 Contacts deletion: should remove the contact in domain contact

docs/modules/ROOT/pages/tmail-backend/webadmin.adoc, tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/firebase/CassandraFirebaseSubscriptionDAO.scala, tmail-backend/jmap/extensions-cassandra/src/main/scala/com/linagora/tmail/james/jmap/firebase/CassandraFirebaseSubscriptionRepository.scala, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebaseSubscriptionRepository.java, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebaseSubscriptionUserDeletionTaskStep.java, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/MemoryFirebaseSubscriptionRepository.java, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/firebase/FirebaseSubscriptionRepositoryContract.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/firebase/FirebaseSubscriptionUserDeletionTaskStepTest.scala
resolve https://github.com/linagora/tmail-backend/issues/668
IT part: required setup of real FCM credentials, I would rather skip it.
For deleting the FCM token on FCM, I do not see the Firebase admin SDK supporting any API like that.
=> FCM subscriptions deletion

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
Otherwise, `tmail.linagora.com` would not function normally without JMAP listeners, in the next release.
=> [FIX] Missing JMAP listeners module in Distributed ES6

Jenkinsfile
When the ci test fails, We can click on "Tests" on the Jenkin board to quickly get the names of test cases that failed. (it will be easier than reading the noise logs)
=> [CI] Jenkinsfile - Recording Test Results and Archiving Artifacts

tmail-backend/apps/distributed/src/main/conf/usersrepository.xml
supportsVirtualHosting is only for ReadOnlyUsersRepository.
=> [FIX] CombinedUsersRepository configuration sample should use `enableVirtualHosting` instead of `supportsVirtualHosting`

tmail-backend/apps/distributed-es6-backport/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
- Delete queue `taskManagerQueue` manually on preprod, then tmail-backend will re-created it 
Right now it is `classic` , but after the commit https://github.com/apache/james-project/commit/33d5b2843043ed4604d792c2ea7c6964a27b3e78 it will be `quorum`
=> Update James SHA-1

Jenkinsfile, pom.xml, tmail-backend/apps/distributed-es6-backport/pom.xml, tmail-backend/apps/distributed/pom.xml, tmail-backend/apps/memory/pom.xml
Developers who use computers based on ARM CPU (e.g.: mobile team with MacBook, and me sometimes), will get poor performance. 
- JIB supports it (only `jib:build` goal) https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image
- Create a new maven profile ("ci") for the configuration of multi-platform
- Jenkinsfile will use "CI" profile for the Delivery image
- The Docker hub looks like this:
- When running the `tmail-backend-memory` image on the arm CPU, it automatically fetches exactly os/arch by manifest
=> [BUILD] Build multi-platform (amd64/arm64) for docker image by JIB

demo/apisix/conf/apisix.yaml
resolve https://github.com/linagora/james-project/issues/5074
=> ISSUE-640 Apisix - plugin - client control for setting the max size of the client request body

tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/TestRabbitMQModule.java, tmail-backend/jmap/extensions-rabbitmq/src/main/java/com/linagora/tmail/james/jmap/RabbitMQEmailAddressContactConfiguration.java, tmail-backend/jmap/extensions-rabbitmq/src/test/java/com/linagora/tmail/james/jmap/RabbitMQEmailAddressContactConfigurationTest.java, tmail-backend/jmap/extensions-rabbitmq/src/test/java/com/linagora/tmail/james/jmap/RabbitMQEmailAddressContactSubscriberTest.java
Getting the vhost from the uri should be a fallback in case it's not present, like for other queues definition
Note: The fact that we don't have those queues in the vhost in most of our deployments is because we don't add it in the `address.contact.uri` parameter.
=> Force vhost parameter for RabbitMQ on address contact queues

tmail-backend/integration-tests/jmap/postgres-jmap-integration-tests/src/test/java/com/linagora/tmail/james/PostgresEmailQueryMethodTest.java
after https://github.com/apache/james-project/pull/2183
=> ISSUE-919 Integration tests for TMail JMAP - Remove "@Disabled" test in PostgresEmailQueryMethod

tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebasePushClient.java
cf: https://github.com/linagora/tmail-backend/commit/43c49615a06edb850fdd7d4b35fbd05873dfc6af#r141977107
cc @tddang-linagora I deployed this fix on staging.
=> [FIX] FCM: do not flag background update (`content-available=1`) for EmailDelivery notifications

demo/apisix/conf/apisix.yaml
As public asset could be accessed from any website/origin.
Before e.g. `allow_origins: "https://tmail.linagora.com"`
After: `allow_origins: "*"`
=> ISSUE-1046 Public Asset preflight request should allow wildcard origins

demo/docker-compose.yml, pom.xml, tmail-backend/apps/distributed/docker-compose.yml
When the container exits with an error code > 0 (except `docker stop`), the container will be restarted automatically by Docker daemon.
https://github.com/user-attachments/assets/605026fb-2683-4239-a152-1fc775c74bac
Docker health check is not related to this Docker restart policy.
But if we want to customize the restart condition, we can combine Docker health check + a script to monitor the container's health status.
=> ISSUE-1124 Apply docker restart policy: restart on failure

tmail-backend/apps/distributed/docker-compose.yml, tmail-backend/apps/distributed/monitor_health.sh
- tmail-backend container would be marked as `healthy` after it fully started.
- tmail-backend container would be restarted upon the container being `unhealthy`, until it is `healthy` again.
https://github.com/user-attachments/assets/c7b83427-e7f7-483d-804b-0326f97d56a2
=> ISSUE-1124 Implement liveness-like for tmail-backend container

demo/apisix/tmail-apisix-plugin-runner/README.md, demo/apisix/tmail-apisix-plugin-runner/src/main/java/com/linagora/apisix/plugin/AppConfiguration.java, demo/apisix/tmail-apisix-plugin-runner/src/main/resources/application.yaml, demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/ClusterRedisRevokedTokenRepositoryTest.java, demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/RedisMasterReplicaRevokedTokenRepositoryTest.java, demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/RedisRevokedTokenRepositoryTest.java, demo/apisix/tmail-apisix-plugin-runner/src/test/java/com/linagora/apisix/plugin/RedisSentinelRevokedTokenRepositoryTest.java
For [MU] deployment, SSO, Apisix, and Redis Sentinel are required.
The current `tmail-apisix-plugin-runner` does not support configuration parsing for Sentinel.
- Rename `ClusterRedisRevokedTokenRepositoryTest` -> `RedisMasterReplicaRevokedTokenRepositoryTest`
to reflect the master-replica topology of the test container, reducing potential confusion.
- `RedisSentinelRevokedTokenRepositoryTest`: Placeholder for a manual test (I performed it, and it works).
- :white_check_mark: Rebuild the image `linagora/apisix:3.2.0-debian-javaplugin` and successfully start it with Redis Sentinel.
=> ISSUE-624 Apisix plugin runner - support redis sentinel

demo/apisix/README.md, demo/apisix/tmail-apisix-plugin-runner/README.md, demo/docker-compose.yml
Pushed `linagora/apisix:3.2.0-debian-sentinel-javaplugin` to the linagora docker repo already
=> ISSUE-624 New tag for Linagora apisix image

demo/apisix/Dockerfile, demo/apisix/README.md, demo/apisix/tmail-apisix-plugin-runner/README.md, demo/docker-compose.yml
From the local docker compose test I could check quickly it seems to still work. But let's test it first on a staging environment before moving to it
=> Upgrade apisix base image to 3.9.1-debian

tmail-backend/apps/postgres/sample-configuration/listeners.xml
I saw a lot of time we missed it when "demo, deploy..."
It would be better to define it as default.
=> [PGSQL] Update default conf - Add PopulateEmailQueryViewListener to listeners.xml

tmail-backend/apps/distributed/src/main/conf/listeners.xml, tmail-backend/apps/memory/src/main/conf/listeners.xml
I saw a lot of time we missed it when "demo, deploy..." 
It would be better to define it as default.
=> Update default conf - Add PopulateEmailQueryViewListener to listeners.xml

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc, tmail-backend/apps/distributed/src/main/conf/deletedMessageVault.properties, tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedJamesConfiguration.java, tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/AwsS3BlobStoreExtension.java, tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/DistributedServerWithoutDeletedMessageVaultTest.java, tmail-backend/apps/distributed/src/test/resources/eml/htmlMail.eml
If the vault is disabled, it should not bind related classes and not create a bucket on s3 either.
=> Add a module chooser for deleted message vault on distributed server

tmail-backend/apps/postgres/src/main/scripts/james-cli
GIVEN I run james-cli in kubernetes
THEN the pod crashes and reboots
Because the james-cli runs JVM it catches the environment variables set by James. As such it always pretouch 3GB of RAM. When added to memory consumed by James it exceeds the limit and pod get's OOM-killed.
=> Postgres-app: unset JAVA_TOOL_OPTIONS env variable when running james-cli

tmail-backend/apps/distributed/src/main/scripts/james-cli, tmail-backend/apps/memory/src/main/scripts/james-cli
GIVEN I run james-cli in kubernetes
THEN the pod crashes and reboots
Because the james-cli runs JVM it catches the environment variables set by James. As such it always pretouch 3GB of RAM. When added to memory consumed by James it exceeds the limit and pod get's OOM-killed.
=> TMail: unset JAVA_TOOL_OPTIONS env variable when running james-cli

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java
- It should be installed single time by `choosePop3ServerModule` method
// Fix miss code of pr https://github.com/linagora/tmail-backend/pull/1180/files
=> Fixup Guice install POP3ServerModule 2 times

tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventReplyWithAMQPWorkflowTest.java, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/resources/mailetcontainer_with_amqpforward_openpass.xml
Error when deploying prod:
{"timestamp":"2024-09-19T02:00:09.101Z","level":"ERROR","thread":"main","logger":"org.apache.james.mailetcontainer.lib.AbstractStateMailetProcessor","message":"Caused by nested exception: ","context":"default","exception":"com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'collector:email' in vhost '/': received 'direct' but current is 'fanout', class-id=40, method-id=10)
Need to include the AMQP hotfix: https://github.com/apache/james-project/pull/2412
=> Update James SHA1

demo/apisix/conf/apisix.yaml, demo/tmail/jmap.properties, docs/modules/ROOT/pages/tmail-backend/jmap-extensions/ticketAuthentication.adoc, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/TicketSerializer.scala
Frontend team start to integrate WebSocket.
Browser does not support sending Authorization header upon HTTP handshake request => solution: https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/ticketAuthentication.adoc
We need to expose the route via APISIX.
=> ISSUE-1192 Apisix: enable ticket route

pom.xml
Because support of non LTS java version ends with the newer versions...
=> Adopt JRE 23

tmail-backend/jmap/extensions-opensearch/src/main/java/com/linagora/tmail/james/jmap/OpenSearchContactConfiguration.java, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/contact/EmailAddressContactSearchEngineContract.scala
Previously, prefix search for first name/surname works but only with at least 3 chars. Reason: to not return too noise suggestions, and save indexing space.
However, Diana seems to have requested this to be able to search with fewer characters. Verified with GMail that supports autocomplete addresses from 1 char though.
TODO: testing and document index (settings) migration steps.
=> ISSUE-1204 Autocomplete prefix search for names

tmail-backend/apps/distributed/docker-compose.yml, tmail-backend/apps/distributed/pom.xml, tmail-backend/apps/memory/pom.xml
- Using curl to prevent the creation of a temporary file by wget
another solution of https://github.com/linagora/tmail-backend/pull/1210
We should choose one.
Now `wget` is still enough, but `curl` offers a more comprehensive response
=> Install curl to docker image, then using curl for healthcheck

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc
Otherwise, we have metric keys conflict between 2 blob stores: 
```java
09:00:22.679 [INFO ] o.a.j.CONFIGURATION - Load configuration file /root/conf/blob.properties 
09:00:22.899 [ERROR] o.a.j.GuiceJamesServer - Fatal error while starting James java.lang.IllegalArgumentException: A metric named s3_httpClient_availableConcurrency already exists
at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:168)
at org.apache.james.metrics.dropwizard.DropWizardGaugeRegistry.settableGauge(DropWizardGaugeRegistry.java:53)
at org.apache.james.blob.objectstorage.aws.JamesS3MetricPublisher.<init>(JamesS3MetricPublisher.java:45)
at org.apache.james.blob.objectstorage.aws.S3ClientFactory.lambda$new$0(S3ClientFactory.java:92)
```
cc @hungphan227
=> ISSUE-1198 Add docs for disable S3 metrics

pom.xml, tmail-backend/apps/distributed/src/main/conf/jvm.properties
- Better convenient as this is our common path to use too.
- Match default behavior with James apps
=> [IMPROVEMENT] Set default `-Dextra.props=/root/conf/jvm.properties` for TMail apps

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc, tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EmailRecoveryActionGetMethodContract.scala, tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/EmailRecoveryActionSetMethodContract.scala, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/resources/jmap.properties, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/EmailRecoveryActionSetMethod.scala
cf [this issue](https://github.com/linagora/tmail-backend/issues/1201)
i caught the request on the fly to add a new criterion preventing unwanted results to show up.
i am currently learning how `UpdatableTickingClock` works to write a test about this.
=> ISSUE-1201 User Limit For Mail Restoration

tmail-backend/tmail-third-party/openpaas/pom.xml, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/HttpUtils.java, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/OpenPaasConfiguration.java, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/api/OpenPaasRestClient.java, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/api/OpenPaasRestClientException.java, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/api/OpenPaasUserResponse.java, tmail-backend/tmail-third-party/openpaas/src/test/scala/com/linagora/tmail/api/OpenPaasRestClientTest.java, tmail-backend/tmail-third-party/openpaas/src/test/scala/com/linagora/tmail/api/OpenPaasServerExtension.scala, tmail-backend/tmail-third-party/pom.xml
=> [ISSUE-1163] Implement OpenPaasRestClient

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraContactSupportCapabilityContract.scala, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraContactSupportCapabilityTest.java
Followup to https://github.com/linagora/tmail-backend/pull/1230
reason: nested test classes weren't being picked up.
=> Fix tests in nested class not being executed

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc, tmail-backend/blob/secondary-blob-store/src/main/java/com/linagora/tmail/blob/secondaryblobstore/FailedBlobOperationListener.java, tmail-backend/blob/secondary-blob-store/src/main/java/com/linagora/tmail/blob/secondaryblobstore/SecondaryBlobStoreDAO.java, tmail-backend/blob/secondary-blob-store/src/test/java/com/linagora/tmail/blob/secondaryblobstore/SecondaryBlobStoreDAOTest.java, tmail-backend/blob/secondary-blob-store/src/test/java/com/linagora/tmail/blob/secondaryblobstore/SecondaryBlobStoreDAOWithEmptySuffixTest.java, tmail-backend/guice/blob-guice/src/main/java/com/linagora/tmail/blob/guice/BlobStoreConfiguration.java, tmail-backend/guice/blob-guice/src/main/java/com/linagora/tmail/blob/guice/BlobStoreModulesChooser.java, tmail-backend/guice/blob-guice/src/main/java/com/linagora/tmail/blob/guice/SecondaryS3BlobStoreConfiguration.java, tmail-backend/guice/blob-guice/src/main/java/com/linagora/tmail/blob/guice/SecondaryS3BlobStoreConfigurationReader.java, tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraSecondaryBlobStoreTest.java
=> ISSUE-1307 Allow to specify secondary bucket suffix

tmail-backend/tmail-third-party/ai-bot/src/test/java/com/linagora/tmail/mailet/AIBotIntegrationTest.java
Today, many CI jobs failed because of this, (always fail on the local computer)
Disable until resolving by https://github.com/linagora/tmail-backend/issues/1303
=> [CI] Disable unstable test: AIBotIntegrationTest

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java, tmail-backend/deployment-tests/common/src/main/java/com/linagora/tmail/deployment/ImapAndSmtpContract.java, tmail-backend/deployment-tests/common/src/main/java/com/linagora/tmail/deployment/TMailDeploymentValidation.java, tmail-backend/deployment-tests/common/src/main/resources/com/linagora/tmail/deployment/scripts/SelectThenFetchWithExistingMessages.test, tmail-backend/deployment-tests/common/src/main/resources/com/linagora/tmail/deployment/scripts/ValidateDeployment.test, tmail-backend/imap-extensions/pom.xml, tmail-backend/imap-extensions/src/main/java/com/linagora/tmail/imap/TMailIMAPModule.java, tmail-backend/imap-extensions/src/main/java/com/linagora/tmail/imap/TMailNamespaceSupplier.java, tmail-backend/imap-extensions/src/main/java/com/linagora/tmail/imap/TMailPathConverter.java, tmail-backend/imap-extensions/src/test/java/imap/linagora/tmail/imap/TMailPathConverterTest.java, tmail-backend/imap-extensions/src/test/java/imap/linagora/tmail/imap/TeamMailboxPathConverterContract.java, tmail-backend/integration-tests/imap/memory-imap-integration-tests/src/test/java/com/linagora/tmail/imap/IMAPTeamMailboxIntegrationTest.java, tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailbox.scala
resolve https://github.com/linagora/tmail-backend/issues/1272
=> ISSUE-1272 Team mailboxes over IMAP

tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/firebase/FirebasePushClient.java
Useful to spot the FCM timeout error for example:
```json
{
"timestamp": "2024-11-26T09:47:47.295Z",
"level": "ERROR",
"thread": "firebase-default-0",
"logger": "com.linagora.tmail.james.jmap.firebase.FirebasePushClient",
"message": "Error when pushing FCM notification",
"context": "default",
"exception": "com.google.firebase.messaging.FirebaseMessagingException: Timed out while making an API call: Error getting access token for service account: Connect timed out, iss: firebase-adminsdk-9scwt@fir-jmap-poc.iam.gserviceaccount.com\n\tat com.google.firebase.messaging.FirebaseMessagingException.withMessagingErrorCode(FirebaseMessagingException.java:51)\n\tat com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:293)\n\t …
```
=> [FCM] Add error log for FCM push

docs/modules/ROOT/pages/tmail-backend/configure/index.adoc
Otherwise, RabbitMQ Management API failure makes TMail can not start for example.
=> [DOC] FCM via proxy: add JVM property to exclude proxy usage

docs/modules/ROOT/pages/tmail-backend/configure/ecosystem-discovery.adoc, docs/modules/ROOT/pages/tmail-backend/configure/index.adoc, tmail-backend/apps/distributed/src/main/conf/linagora-ecosystem.properties, tmail-backend/apps/memory/src/main/conf/linagora-ecosystem.properties, tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraServicesDiscoveryRoutesContract.scala, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/resources/linagora-ecosystem.properties, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/service/discovery/LinagoraServicesDiscoveryRoutes.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/LinagoraServicesDiscoveryConfigurationSerializeTest.scala
resolve https://github.com/linagora/tmail-backend/issues/1289
=> ISSUE-1289 Mobile APP app grid

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraSecondaryBlobStoreTest.java
Many CI tests failed due to an unstable test in this class. 
We have already created a ticket to investigate: https://github.com/linagora/tmail-backend/issues/1299
=> ISSUE-1299 - Temporary disable DistributedLinagoraSecondaryBlobStoreTest (flaky test)

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/api/OpenPaasRestClient.java
Because I've seen this log too many times without really necessary knowing what userId it was about
=> [ISSUE-1163] Add userId to error log when issue with Openpaas client

pom.xml, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/pom.xml, tmail-backend/tmail-third-party/openpaas/pom.xml
This should be the default, disabled where it fails.
We are loosing so much build time...
=> Reuse forks

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/ContactRabbitMqMessage.java, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/OpenPaasContactsConsumer.java, tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/OpenPaasContactsConsumerTest.java
tackling the Synchronise contact delete #1275 and Synchronise contact update #1274 issues
i basically created two more exchanges and two more queues, and depending on the queue, the message is treated differently (new `updateContact` and `deleteContact` similar to the existing `indexContactIfNeeded`).
since the key for these `index`, `update`, `delete` operations is the `accountId` which is obtained through the mail address, the entry is correctly updated when the address does not change (previous entry replaced by the new one, cf the test `contactShouldBeUpdatedWhenContactUserUpdatedMessageWithSameAddress`), whereas if the address is updated then both the old and the new entries are there (cf the test `newContactShouldBeAddedWhenContactUserUpdatedMessageWithUpdatedAddress`)
=> synchronize tmail's auto-complete database after openpaas user update/delete operations

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/ContactRabbitMqMessage.java, tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/OpenPaasContactsConsumerTest.java
resolve https://github.com/linagora/tmail-backend/issues/1392#issuecomment-2551167506
=> ISSUE-1392 OpenPaasContactsConsumer - fallback _id to userId when empty

tmail-backend/apps/distributed/pom.xml, tmail-backend/apps/memory/pom.xml
Spotted while attempting to run Glowroot in `linagora/tmail-backend:memory-1.0.1` to gather metrics.
Error:
```
java.lang.IllegalArgumentException: Unsupported class file major version 67
2025-01-02T08:06:18.214431500Z 	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
```
We should upgrade glowroot to support java 21
=> Upgrade glowroot to v0.14.2 (support java 21)

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/calendarEventReply.adoc, tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventAttendanceGetMethodContract.scala, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraCalendarEventAttendanceGetMethodTest.java, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/EventAttendanceRepository.java, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/MessagePartBlobId.java, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/StandaloneEventAttendanceRepository.java, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/CalendarEventAttendanceSerializer.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventAttendanceGetMethod.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventParseMethod.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/StandaloneEventAttendanceRepositoryTest.scala
=> Introduce the CalendarEventAttendance/get JMAP method

tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/TmailEventSerializer.java, tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/DistributedLinagoraSecondaryBlobStoreTest.java
When putting back the distributed integration tests for secondary blobstore, it was broken. I think tmaileventserializer is used by the secondary blobstore, and does not support multiple event serialization. After fixing this the tests are green.
@chibenwa what version of tmail running on cnb prod? could the secondary blobstore been affected lately?
=> ISSUE-1299 Fix DistributedLinagoraSecondaryBlobStoreTest and TmailEventSerializer

tmail-backend/imap-extensions/src/test/java/org/apache/james/imap/main/TMailPathConverterTest.java, tmail-backend/imap-extensions/src/test/java/org/apache/james/imap/main/TeamMailboxPathConverterContract.java, tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailbox.scala
@chibenwa As promised in #1405, this PR ensures TeamMailboxes work with [the newly introduced configurable path delimiter](https://github.com/apache/james-project/pull/2588) and adjusts the `TmailPathConverterTests` accordingly.
=> (JAMES-4099) Ensure TeamMailboxes work with newly introduced configurable mailbox path delimiter

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/data/data-rabbitmq/pom.xml, tmail-backend/data/data-rabbitmq/src/main/java/com/linagora/tmail/DisconnectorRequestSerializer.java, tmail-backend/data/data-rabbitmq/src/main/java/com/linagora/tmail/RabbitMQDisconnectorConsumer.java, tmail-backend/data/data-rabbitmq/src/main/java/com/linagora/tmail/RabbitMQDisconnectorNotifier.java, tmail-backend/data/data-rabbitmq/src/main/java/com/linagora/tmail/RabbitMQDisconnectorOperator.java, tmail-backend/data/data-rabbitmq/src/test/java/com/linagora/tmail/DisconnectorRequestSerializerTest.java, tmail-backend/data/data-rabbitmq/src/test/java/com/linagora/tmail/RabbitMQDisconnectorConsumerTest.java, tmail-backend/guice/distributed/pom.xml, tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/RabbitMQDisconnectorModule.java, tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/ScheduledReconnectionHandler.java, tmail-backend/integration-tests/webadmin/distributed-webadmin-integration-tests/src/test/java/com/linagora/tmail/integration/distributed/DistributedProtocolServerIntegrationTest.java, tmail-backend/integration-tests/webadmin/webadmin-integration-tests-common/src/main/java/com/linagora/tmail/integration/TestFixture.java, tmail-backend/pom.xml, tmail-backend/webadmin/webadmin-protocols/pom.xml, tmail-backend/webadmin/webadmin-protocols/src/test/java/com/linagora/tmail/DisconnectionRouteTest.java, tmail-backend/webadmin/webadmin-protocols/src/test/java/com/linagora/tmail/TestConnectionDisconnector.java
resolve https://github.com/linagora/james-project/issues/5334
- https://github.com/apache/james-project/pull/2603
=> ISSUE-5334 Disconnection: the distributed way

docs/modules/ROOT/pages/tmail-backend/jmap-extensions/downloadAll.adoc, tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/DownloadAllContract.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/routes/DownloadAllRoutes.scala
resolve https://github.com/linagora/tmail-backend/issues/1511
=> ISSUE-1511 Fix downloadAll endpoint in session capability

tmail-backend/tmail-third-party/openpaas/src/test/resources/docker-openpaas-setup.yml
Closes #1537
I could not health check all services using the OpenPaas API `/api/healthcheck/{services}` as some images don't have CURL installed.  As a workaround, I’ve implemented custom health checks for these services
=> Healthcheck services in 'docker-openpaas-setup' docker compose file

tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/oidc/WebFingerRoutes.scala
The redirection to the oidc url openid configuration endpoint should be the oidc url defined in jmap.properties suffixed by `.well-known/openid-configuration` (which is defined by the openid connect spec cf https://openid.net/specs/openid-connect-discovery-1_0.html
=> [Fix] Proper redirect to the oidc openid configuration endpoint

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/JCardObjectDeserializer.java, tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/contact/JCardObjectDeserializerTest.java
Spotted on MU preprod:
```java
{
"timestamp": "2025-03-10T06:01:25.790Z",
"level": "INFO",
"thread": "rabbitmq-driver-8",
"logger": "com.linagora.tmail.contact.JCardObjectDeserializer",
"message": "Invalid contact mail address 'mailto:test21@test.org' found in JCard Object",
"context": "default"
}
```
=> JCardObjectDeserializer: sanitize `mailto:` prefix

tmail-backend/jmap/extensions-api/src/main/java/com/linagora/tmail/james/jmap/AttendanceStatus.java, tmail-backend/jmap/extensions-api/src/main/java/com/linagora/tmail/james/jmap/EventAttendanceRepository.java, tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventAttendanceResults.scala, tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventReplyResults.scala, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/StandaloneEventAttendanceRepository.java, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/TMailJMAPModule.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventAcceptMethod.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventAttendanceGetMethod.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventMaybeMethod.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventRejectMethod.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventReplyPerformer.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventReply.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/StandaloneEventAttendanceRepositoryTest.scala, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/dav/CalDavEventAttendanceRepository.java
When I Implementing:
- https://github.com/linagora/tmail-backend/issues/1567
I see a lot of boilerplate in the EventAttendanceRepository 
reason when try to repeated convert `blobId` between scala <-> java in several times.
The code difficult to read.
And the keep of old code `CalendarEventReplyPerformer` make we parsable blobId twice time, it is un necessary. 
So this pr: 
- Reducing boilerplat
- Avoid parse blobId twice time
=> ISSUE-1400 Refactor EventAttendanceRepository & related classes

tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/cassandra/CassandraBlobIdListDAO.scala, tmail-backend/blob/blobid-list/src/main/java/com/linagora/tmail/blob/blobid/list/cassandra/CassandraBlobIdListModule.scala
The system property is purely cosmetic to allow control if needed hence the lack of documentation (better than a constant)
=> [ENHANCEMENT] TTL for blobIdList

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/DistributedServerWithPureRabbitMQEventBusTest.java, tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/DistributedServerWithRedisEventBusKeysTest.java, tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/ScheduledReconnectionHandlerProbe.java, tmail-backend/apps/distributed/src/test/java/com/linagora/tmail/james/app/SchedulerReconnectionHandlerIntegrationTest.java, tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java, tmail-backend/event-bus-redis/src/main/java/org/apache/james/events/TmailGroupRegistrationHandler.java, tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusTest.java, tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/ScheduledReconnectionHandler.java, tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/DistributedEmailAddressContactEventModule.java, tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/EmailAddressContactRabbitMQEventBusModule.java, tmail-backend/guice/distributed/src/main/java/com/linagora/tmail/event/RabbitMQAndRedisEventBusModule.java
This needs https://github.com/apache/james-project/pull/2685.
This resolves:
- https://github.com/linagora/james-project/issues/5421
- https://github.com/linagora/tmail-backend/issues/1609
=> Multiple fixes for Redis event bus

tmail-backend/apps/distributed/src/main/java/com/linagora/tmail/james/app/DistributedServer.java, tmail-backend/apps/memory/src/main/java/com/linagora/tmail/james/app/MemoryServer.java, tmail-backend/apps/postgres/src/main/java/com/linagora/tmail/james/app/PostgresTmailServer.java, tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/CalendarEventCounterAcceptMethodContract.scala, tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/CalendarEventSupportCapabilityContract.scala, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventCounterAcceptMethodTest.java, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventSupportCapabilityTest.java, tmail-backend/jmap/extensions-api/src/main/java/com/linagora/tmail/james/jmap/CalendarEventNotFoundException.java, tmail-backend/jmap/extensions-api/src/main/java/com/linagora/tmail/james/jmap/CalendarEventRepository.java, tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventModifier.scala, tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/calendar/CalendarResolver.scala, tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventParse.scala, tmail-backend/jmap/extensions-api/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventHelper.scala, tmail-backend/jmap/extensions-api/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventModifierTest.scala, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/StandaloneEventRepository.java, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/TMailJMAPModule.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/json/CalendarEventCounterSerializer.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventCounterAcceptMethod.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventCounterPerformer.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/CalendarEventParseMethod.scala, tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventCounter.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/StandaloneEventRepositoryTest.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/calendar/CalendarEventParsedTest.scala, tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/json/CalendarEventCounterSerializerTest.scala, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/OpenPaasModule.java, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/dav/CalDavEventRepository.java, tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/dav/DavCalendarObject.java, tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/CalDavEventRepositoryTest.java, tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/DockerOpenPaasSetup.java
resolve https://github.com/linagora/tmail-backend/issues/1255
=> ISSUE-1255 Implement JMAP CalendarEventCounter/accept method

tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/openpaas/DistributedOpenPaaSCalendarEventAcceptMethodTest.java, tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/openpaas/DistributedOpenPaaSCalendarEventMaybeMethodTest.java, tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/openpaas/DistributedOpenPaaSCalendarEventRejectMethodTest.java, tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/java/com/linagora/tmail/james/openpaas/OpenpaasTestUtils.java, tmail-backend/integration-tests/jmap/distributed-jmap-integration-tests/src/test/resources/mailetcontainer_openpaas_dav.xml, tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/java/com/linagora/tmail/common/TemporaryTmailServerUtils.java, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventCounterAcceptMethodTest.java, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventReplyWithAMQPWorkflowTest.java, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryCalendarEventSupportCapabilityTest.java, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/MemoryLinagoraCalendarEventAttendanceGetMethodTest.java, tmail-backend/integration-tests/jmap/memory-jmap-integration-tests/src/test/java/com/linagora/tmail/james/openpaas/OpenpaasTestUtils.java
This PR makes it easier to write test classes with the Guice James server, ensuring independence from specific configuration files and avoiding mixing them into a single file, such as `mailetcontainer.xml`.
=> Openpaas Module - Improve test class isolation for Guice server

twake-calendar-side-service/calendar-rest-api/src/main/java/com/linagora/calendar/restapi/FallbackProxy.java
The current log without HTTP Method make confuse for "guess" which feature is missing
Eg:
```
10:01:13.508 [WARN ] c.l.c.r.FallbackProxy - Proxying /api/users/5f50a663bdaffe002629099c
```
Maybe it is UPDATE api
not GET
=> [ENHANCEMENT] Log HTTP method of request when fallback proxying

tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RedisEventBusServiceSentinelTest.java
The fix conducted in https://github.com/linagora/tmail-backend/pull/1685 seems to work with this new introduction test.
I tried as well before the sha-1 upgrade and fix and it fails. 
PubSub according to Lettuce doc seems to be mainly for standalone and cluster. I think that's why standalone connections have been forced master/replica and sentinel. However there is still some normal connections I think for registering groups and dispatching events for example. Those were also on a standalone connection.
The fix puts sentinel and master/replica connections on normal connections and forces a pubSub connection to the redis sentinel uri. It seems better now at least with those tests.
=> Redis event bus sentinel failover test

tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RedisEventBusServiceSentinelTest.java
20s was too close to the limit for failover process to finish (even locally) and made it unstable
I wuld guess that with other tests running in parallel it might take longer sometimes
=> [JAMES-3693] Up the await time for RedisEventBusServiceSentinelTest

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/mailet/CalDavCollect.java, tmail-backend/tmail-third-party/openpaas/src/test/java/com/linagora/tmail/CalDavCollectIntegrationTest.java
Draft for now, as the fixup! with the extra test allowed me to catch an other issue.
In fact ICALToJsonAttribute is storing json attributes per each recipient...
In CalDavCollect we process each json attribute... and loop on each mail recipient. 
So on that extra test I still can see a 400 call to caldav but for the correct receiver user because... we do the request twice in that scenario. First request is fine, second is a fail
We should just likely only loop on json attributes and extract the recipient from it, and not looping again on the list of recipients.
Will fix tomorrow.
Don't hesitate to give early feedback.
I thought as well about filtering on ICALToJsonAttribute but that implies a james code change, which I'm not sure is justified.
=> Should not send request to caldav server when recipient is not part of the attendee list

tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/java/com/linagora/tmail/common/OidcAuthenticationContract.java, tmail-backend/jmap/extensions-redis/src/main/java/com/linagora/tmail/james/jmap/oidc/RedisOidcTokenCache.java, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/oidc/OidcAuthenticationStrategy.java, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/oidc/OidcEndpointsInfoResolver.java, tmail-backend/jmap/extensions/src/main/java/com/linagora/tmail/james/jmap/oidc/TokenInfo.java, tmail-backend/jmap/extensions/src/test/java/com/linagora/tmail/james/jmap/oidc/OidcTokenCacheContract.java
If OIDC server does not return `aud` as part of the introspection response, we can ignore audience validation.
=> ISSUE-1763 [OIDC] Accept missing `aud` in the introspection response

tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusContractTest.java, tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusTest.java, tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusWithKvrocksSentinelTest.java, tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusWithKvrocksTest.java, tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RabbitMQAndRedisEventBusWithRedisSentinelTest.java, tmail-backend/event-bus-redis/src/test/java/org/apache/james/events/RedisEventBusServiceTest.java
- Polish some tests from pausing RabbitMQ -> pausing Redis instead. 
- For the tests dispatching key events for EXISTING registration after restarting Redis, simply remove them because Redis is not persistent by default. 
- For the test dispatching key events for NEW registration after restarting Redis, remove it because it has been covered by the `RedisStandaloneRestart.newNotificationRegistrationShouldWorkWellAfterRedisRestartTest` test.
=> ISSUE-1687 Revise RabbitMQAndRedisEventBusContractTest test suite

tmail-backend/tmail-third-party/openpaas/src/main/java/com/linagora/tmail/contact/SabreContactsConsumer.java
3000 timeout errors during the spam campaign:
```java
{"timestamp":"2025-06-11T07:51:31.593Z","level":"ERROR","thread":"reactor-http-epoll-3","logger":"com.linagora.tmail.contact.SabreContactsConsumer","message":"Error when consume message","context":"default","exception":"com.linagora.tmail.api.OpenPaasRestClientException: Failed to retrieve user mail using OpenPaas id 67537d58c3a168001bf7d02e
at com.linagora.tmail.api.OpenPaasRestClient.lambda$retrieveMailAddress$3(OpenPaasRestClient.java:88)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)
at …
```
=> [IMPROVEMENT] SabreContactsConsumer: better control consumer concurrency

tmail-backend/tmail-third-party/openpaas/src/test/resources/docker-openpaas-setup.yml
OpenPaaS ESN does not work well with RabbitMQ 4.1+ versions because this version introduces a `frame_max` breaking change that requires Node.js amqplib library upgrade.
"amqplib versions older than 0.10.7 will not be able to connect to RabbitMQ 4.1.0 and later versions due to the initial AMQP 0-9-1 maximum frame size increase covered above."
cf: https://github.com/rabbitmq/rabbitmq-server/releases/tag/v4.1.0
=> JAMES-4138 [TMail] Update RabbitMQ 4.0.9 for OpenPaaS integration tests

tmail-backend/tmail-third-party/ai-bot/README.md, tmail-backend/tmail-third-party/ai-bot/sample_conf/mailetcontainer.xml
Closes #1803
Updated the AIBot documentation with security warnings so the reader is invited to use the Apache James rate-limiting mailet. Rate-limiting is a suitable mitigation against Denial of Service and [Denial of Wallet](https://genai.owasp.org/llmrisk/llm102025-unbounded-consumption/) attacks.
Suggested limiting LLM output length to defend against DoW.
=> ISSUE-1803 Implement rate-limiting for AIBot

tmail-backend/pom.xml
In version 9.5.0 systematic timeouts are observed with current code base. Revert.
=> Switch firebase back to 9.3.0

tmail-backend/jmap/extensions-api/src/main/scala/com/linagora/tmail/james/jmap/model/CalendarEventReplyResults.scala
`
{"timestamp":"2025-07-24T08:22:15.262Z","level":"ERROR","thread":"reactor-http-epoll-2","logger":"com.linagora.tmail.james.jmap.model.CalendarEventReplyResults","message":"serverFail to generate reply mail for abc@xyz.org","context":"default","exception":"com.linagora.tmail.james.jmap.calendar.CalendarEventModifier$NoUpdateRequiredException: null
    at com.linagora.tmail.james.jmap.calendar.CalendarEventModifier.apply(CalendarEventModifier.scala:143)
`
=> [FIX] CalendarEventReply method should not return NoUpdateRequiredException as serverFail

tmail-backend/saas/saas-cassandra/src/main/java/com/linagora/tmail/saas/api/cassandra/CassandraSaaSAccountRepository.java, tmail-backend/saas/saas-rabbitmq/src/main/java/com/linagora/tmail/saas/rabbitmq/settings/TWPSettingsConsumer.java, tmail-backend/saas/saas-rabbitmq/src/main/java/com/linagora/tmail/saas/rabbitmq/subscription/SaaSSubscriptionConsumer.java
Fix blocking call:
```java
[ERROR] c.l.t.s.r.s.SaaSSubscriptionConsumer - Error when consuming SaaS subscription message
java.lang.IllegalStateException: blockOptional() is blocking, which is not supported in thread reactor-tcp-nio-5
    at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:108)
    at reactor.core.publisher.Mono.blockOptional(Mono.java:1831)
    at org.apache.james.user.postgres.PostgresUsersDAO.getUserByName(PostgresUsersDAO.java:75)
    at org.apache.james.user.lib.UsersRepositoryImpl.getUserByName(UsersRepositoryImpl.java:205)
    at com.linagora.tmail.saas.rabbitmq.subscription.SaaSSubscriptionConsumer.lambda$handleSubscriptionMessage$7(SaaSSubscriptionConsumer.java:191)
    at …
```
=> ISSUE-1884 SaaSSubscriptionConsumer should wrap blocking call usersRepository.getUserByName
